run:
  timeout: 10m

linters:
  enable:
    - gocritic
    - revive
    - nestif
    - gocognit
    - maintidx
    - funlen
    - govet
    - ineffassign
    - reassign
    - goconst
  disable:
    - gocyclo

linters-settings:
  # Alarmas (no refactor hints directos, pero útiles)
  goconst:
    min-len: 2           # detecta strings cortas también
    min-occurrences: 3   # con 2 repeticiones ya obliga a extraer
    match-constant: true # si ya existe const igual, lo usa como match
    ignore-calls: false  # no lo limites solo a args de funciones
    find-duplicates: true
    eval-const-expressions: true
    # opcional: excluir patrones (tokens, IDs, etc.)
    ignore-string-values:
      - '^[0-9a-f]{8,}$'
  gocognit:
    min-complexity: 10

  maintidx:
    # Flaggea funciones con MI < under (más bajo = peor mantenibilidad)
    under: 20

  # Smells concretos
  nestif:
    min-complexity: 4

  funlen:
    lines: 80
    statements: 40
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true

  # go-critic settings (algunos ejemplos de thresholds configurables)
  gocritic:
    enabled-checks:
      - nestingReduce
      - ruleguard
      - boolExprSimplify
    settings:
      ifElseChain:
        minThreshold: 4
      nestingReduce:
        bodyWidth: 4
      ruleguard:
        rules: "ruleguard/rules-*.go"
        enable: "smells"
        failOn: "dsl,import"

issues:
  # Para que el gate sea más “PR-friendly”:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude generated code (aligned with Makefile coverage-gate exclusions, lines 104-107)
  exclude-dirs:
    - internal/infra/sqlite/sqlcgen  # sqlc generated code
    - ruleguard
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"  # Future protobuf generated files
    - ".*_test\\.go$"  # Test files (allowed to be complex, caught by gocyclo instead)
