run:
  timeout: 5m

linters:
  enable:
    - gocritic
    - revive
    - nestif
    - gocognit
    - maintidx
    - funlen
  disable:
    - gocyclo

linters-settings:
  # Alarmas (no refactor hints directos, pero útiles)
  gocognit:
    min-complexity: 10

  maintidx:
    # Flaggea funciones con MI < under (más bajo = peor mantenibilidad)
    under: 20

  # Smells concretos
  nestif:
    min-complexity: 4

  funlen:
    lines: 80
    statements: 40

  # go-critic settings (algunos ejemplos de thresholds configurables)
  gocritic:
    enabled-checks:
      - nestingReduce
      - ruleguard
      - boolExprSimplify
    settings:
      ifElseChain:
        minThreshold: 4
      nestingReduce:
        bodyWidth: 4
      ruleguard:
        rules: "ruleguard/rules-*.go"
        enable: "smells"
        failOn: "dsl,import"

issues:
  # Para que el gate sea más “PR-friendly”:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude generated code (aligned with Makefile coverage-gate exclusions, lines 104-107)
  exclude-dirs:
    - internal/infra/sqlite/sqlcgen  # sqlc generated code
    - ruleguard
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"  # Future protobuf generated files
    - ".*_test\\.go$"  # Test files (allowed to be complex, caught by gocyclo instead)
