// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlcgen

import (
	"context"
)

const countAccountsByWorkspace = `-- name: CountAccountsByWorkspace :one
SELECT COUNT(*) FROM account
WHERE workspace_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) CountAccountsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec

INSERT INTO account (id, workspace_id, name, domain, industry, size_segment, owner_id, address, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	Domain      *string `db:"domain" json:"domain"`
	Industry    *string `db:"industry" json:"industry"`
	SizeSegment *string `db:"size_segment" json:"sizeSegment"`
	OwnerID     string  `db:"owner_id" json:"ownerId"`
	Address     *string `db:"address" json:"address"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

// SQL queries for account table
// Task 1.3.2: sqlc-annotated queries
// IMPORTANT: All account queries filter by workspace_id for multi-tenancy isolation.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Domain,
		arg.Industry,
		arg.SizeSegment,
		arg.OwnerID,
		arg.Address,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, workspace_id, name, domain, industry, size_segment, owner_id, address, metadata, created_at, updated_at, deleted_at
FROM account
WHERE id = ?
  AND workspace_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

type GetAccountByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.WorkspaceID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.SizeSegment,
		&i.OwnerID,
		&i.Address,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many
SELECT id, workspace_id, name, domain, industry, size_segment, owner_id, address, metadata, created_at, updated_at, deleted_at
FROM account
WHERE workspace_id = ?
  AND owner_id = ?
  AND deleted_at IS NULL
ORDER BY name ASC
`

type ListAccountsByOwnerParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	OwnerID     string `db:"owner_id" json:"ownerId"`
}

func (q *Queries) ListAccountsByOwner(ctx context.Context, arg ListAccountsByOwnerParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByOwner, arg.WorkspaceID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.SizeSegment,
			&i.OwnerID,
			&i.Address,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByWorkspace = `-- name: ListAccountsByWorkspace :many
SELECT id, workspace_id, name, domain, industry, size_segment, owner_id, address, metadata, created_at, updated_at, deleted_at
FROM account
WHERE workspace_id = ?
  AND deleted_at IS NULL
ORDER BY name ASC
LIMIT ?
OFFSET ?
`

type ListAccountsByWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListAccountsByWorkspace(ctx context.Context, arg ListAccountsByWorkspaceParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.SizeSegment,
			&i.OwnerID,
			&i.Address,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE account
SET deleted_at = ?,
    updated_at = ?
WHERE id = ?
  AND workspace_id = ?
  AND deleted_at IS NULL
`

type SoftDeleteAccountParams struct {
	DeletedAt   *string `db:"deleted_at" json:"deletedAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAccount,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE account
SET name = ?,
    domain = ?,
    industry = ?,
    size_segment = ?,
    owner_id = ?,
    address = ?,
    metadata = ?,
    updated_at = ?
WHERE id = ?
  AND workspace_id = ?
  AND deleted_at IS NULL
`

type UpdateAccountParams struct {
	Name        string  `db:"name" json:"name"`
	Domain      *string `db:"domain" json:"domain"`
	Industry    *string `db:"industry" json:"industry"`
	SizeSegment *string `db:"size_segment" json:"sizeSegment"`
	OwnerID     string  `db:"owner_id" json:"ownerId"`
	Address     *string `db:"address" json:"address"`
	Metadata    *string `db:"metadata" json:"metadata"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.Domain,
		arg.Industry,
		arg.SizeSegment,
		arg.OwnerID,
		arg.Address,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
