// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const countAgentRunsByAgent = `-- name: CountAgentRunsByAgent :one
SELECT COUNT(*) as count FROM agent_run
WHERE workspace_id = ? AND agent_definition_id = ?
`

type CountAgentRunsByAgentParams struct {
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
}

func (q *Queries) CountAgentRunsByAgent(ctx context.Context, arg CountAgentRunsByAgentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentRunsByAgent, arg.WorkspaceID, arg.AgentDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentRunsByWorkspace = `-- name: CountAgentRunsByWorkspace :one
SELECT COUNT(*) as count FROM agent_run
WHERE workspace_id = ?
`

func (q *Queries) CountAgentRunsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentRunsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentDefinition = `-- name: CreateAgentDefinition :one

INSERT INTO agent_definition (
    id, workspace_id, name, description, agent_type, objective,
    allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id,
    status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', datetime('now'), datetime('now'))
RETURNING id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at
`

type CreateAgentDefinitionParams struct {
	ID                    string          `db:"id" json:"id"`
	WorkspaceID           string          `db:"workspace_id" json:"workspaceId"`
	Name                  string          `db:"name" json:"name"`
	Description           *string         `db:"description" json:"description"`
	AgentType             string          `db:"agent_type" json:"agentType"`
	Objective             json.RawMessage `db:"objective" json:"objective"`
	AllowedTools          json.RawMessage `db:"allowed_tools" json:"allowedTools"`
	Limits                json.RawMessage `db:"limits" json:"limits"`
	TriggerConfig         json.RawMessage `db:"trigger_config" json:"triggerConfig"`
	PolicySetID           *string         `db:"policy_set_id" json:"policySetId"`
	ActivePromptVersionID *string         `db:"active_prompt_version_id" json:"activePromptVersionId"`
}

// Task 3.7: Agent queries
func (q *Queries) CreateAgentDefinition(ctx context.Context, arg CreateAgentDefinitionParams) (AgentDefinition, error) {
	row := q.db.QueryRowContext(ctx, createAgentDefinition,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.AgentType,
		arg.Objective,
		arg.AllowedTools,
		arg.Limits,
		arg.TriggerConfig,
		arg.PolicySetID,
		arg.ActivePromptVersionID,
	)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.AgentType,
		&i.Objective,
		&i.AllowedTools,
		&i.Limits,
		&i.TriggerConfig,
		&i.PolicySetID,
		&i.ActivePromptVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_run (
    id, workspace_id, agent_definition_id, triggered_by_user_id,
    trigger_type, trigger_context, status, inputs,
    retrieval_queries, retrieved_evidence_ids, reasoning_trace,
    tool_calls, output, abstention_reason,
    total_tokens, total_cost, latency_ms, trace_id,
    started_at, completed_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, 'running', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), NULL, datetime('now'))
RETURNING id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at
`

type CreateAgentRunParams struct {
	ID                   string          `db:"id" json:"id"`
	WorkspaceID          string          `db:"workspace_id" json:"workspaceId"`
	AgentDefinitionID    string          `db:"agent_definition_id" json:"agentDefinitionId"`
	TriggeredByUserID    *string         `db:"triggered_by_user_id" json:"triggeredByUserId"`
	TriggerType          string          `db:"trigger_type" json:"triggerType"`
	TriggerContext       json.RawMessage `db:"trigger_context" json:"triggerContext"`
	Inputs               json.RawMessage `db:"inputs" json:"inputs"`
	RetrievalQueries     json.RawMessage `db:"retrieval_queries" json:"retrievalQueries"`
	RetrievedEvidenceIds json.RawMessage `db:"retrieved_evidence_ids" json:"retrievedEvidenceIds"`
	ReasoningTrace       json.RawMessage `db:"reasoning_trace" json:"reasoningTrace"`
	ToolCalls            json.RawMessage `db:"tool_calls" json:"toolCalls"`
	Output               json.RawMessage `db:"output" json:"output"`
	AbstentionReason     *string         `db:"abstention_reason" json:"abstentionReason"`
	TotalTokens          *int64          `db:"total_tokens" json:"totalTokens"`
	TotalCost            *float64        `db:"total_cost" json:"totalCost"`
	LatencyMs            *int64          `db:"latency_ms" json:"latencyMs"`
	TraceID              *string         `db:"trace_id" json:"traceId"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.WorkspaceID,
		arg.AgentDefinitionID,
		arg.TriggeredByUserID,
		arg.TriggerType,
		arg.TriggerContext,
		arg.Inputs,
		arg.RetrievalQueries,
		arg.RetrievedEvidenceIds,
		arg.ReasoningTrace,
		arg.ToolCalls,
		arg.Output,
		arg.AbstentionReason,
		arg.TotalTokens,
		arg.TotalCost,
		arg.LatencyMs,
		arg.TraceID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.Status,
		&i.Inputs,
		&i.RetrievalQueries,
		&i.RetrievedEvidenceIds,
		&i.ReasoningTrace,
		&i.ToolCalls,
		&i.Output,
		&i.AbstentionReason,
		&i.TotalTokens,
		&i.TotalCost,
		&i.LatencyMs,
		&i.TraceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillDefinition = `-- name: CreateSkillDefinition :one
INSERT INTO skill_definition (
    id, workspace_id, name, description, steps, agent_definition_id,
    status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 'draft', datetime('now'), datetime('now'))
RETURNING id, workspace_id, name, description, steps, agent_definition_id, status, created_at, updated_at
`

type CreateSkillDefinitionParams struct {
	ID                string          `db:"id" json:"id"`
	WorkspaceID       string          `db:"workspace_id" json:"workspaceId"`
	Name              string          `db:"name" json:"name"`
	Description       *string         `db:"description" json:"description"`
	Steps             json.RawMessage `db:"steps" json:"steps"`
	AgentDefinitionID *string         `db:"agent_definition_id" json:"agentDefinitionId"`
}

func (q *Queries) CreateSkillDefinition(ctx context.Context, arg CreateSkillDefinitionParams) (SkillDefinition, error) {
	row := q.db.QueryRowContext(ctx, createSkillDefinition,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Steps,
		arg.AgentDefinitionID,
	)
	var i SkillDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentDefinition = `-- name: DeleteAgentDefinition :exec
DELETE FROM agent_definition
WHERE id = ? AND workspace_id = ?
`

type DeleteAgentDefinitionParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteAgentDefinition(ctx context.Context, arg DeleteAgentDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentDefinition, arg.ID, arg.WorkspaceID)
	return err
}

const deleteAgentRun = `-- name: DeleteAgentRun :exec
DELETE FROM agent_run
WHERE id = ? AND workspace_id = ?
`

type DeleteAgentRunParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteAgentRun(ctx context.Context, arg DeleteAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentRun, arg.ID, arg.WorkspaceID)
	return err
}

const deleteSkillDefinition = `-- name: DeleteSkillDefinition :exec
DELETE FROM skill_definition
WHERE id = ? AND workspace_id = ?
`

type DeleteSkillDefinitionParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteSkillDefinition(ctx context.Context, arg DeleteSkillDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkillDefinition, arg.ID, arg.WorkspaceID)
	return err
}

const getAgentDefinitionByID = `-- name: GetAgentDefinitionByID :one
SELECT id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at FROM agent_definition
WHERE id = ? AND workspace_id = ?
LIMIT 1
`

type GetAgentDefinitionByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetAgentDefinitionByID(ctx context.Context, arg GetAgentDefinitionByIDParams) (AgentDefinition, error) {
	row := q.db.QueryRowContext(ctx, getAgentDefinitionByID, arg.ID, arg.WorkspaceID)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.AgentType,
		&i.Objective,
		&i.AllowedTools,
		&i.Limits,
		&i.TriggerConfig,
		&i.PolicySetID,
		&i.ActivePromptVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentDefinitionByName = `-- name: GetAgentDefinitionByName :one
SELECT id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at FROM agent_definition
WHERE workspace_id = ? AND name = ?
LIMIT 1
`

type GetAgentDefinitionByNameParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Name        string `db:"name" json:"name"`
}

func (q *Queries) GetAgentDefinitionByName(ctx context.Context, arg GetAgentDefinitionByNameParams) (AgentDefinition, error) {
	row := q.db.QueryRowContext(ctx, getAgentDefinitionByName, arg.WorkspaceID, arg.Name)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.AgentType,
		&i.Objective,
		&i.AllowedTools,
		&i.Limits,
		&i.TriggerConfig,
		&i.PolicySetID,
		&i.ActivePromptVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentRunByID = `-- name: GetAgentRunByID :one
SELECT id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at FROM agent_run
WHERE id = ? AND workspace_id = ?
LIMIT 1
`

type GetAgentRunByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetAgentRunByID(ctx context.Context, arg GetAgentRunByIDParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, getAgentRunByID, arg.ID, arg.WorkspaceID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.Status,
		&i.Inputs,
		&i.RetrievalQueries,
		&i.RetrievedEvidenceIds,
		&i.ReasoningTrace,
		&i.ToolCalls,
		&i.Output,
		&i.AbstentionReason,
		&i.TotalTokens,
		&i.TotalCost,
		&i.LatencyMs,
		&i.TraceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillDefinitionByID = `-- name: GetSkillDefinitionByID :one
SELECT id, workspace_id, name, description, steps, agent_definition_id, status, created_at, updated_at FROM skill_definition
WHERE id = ? AND workspace_id = ?
LIMIT 1
`

type GetSkillDefinitionByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetSkillDefinitionByID(ctx context.Context, arg GetSkillDefinitionByIDParams) (SkillDefinition, error) {
	row := q.db.QueryRowContext(ctx, getSkillDefinitionByID, arg.ID, arg.WorkspaceID)
	var i SkillDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAgentDefinitionsByWorkspace = `-- name: ListActiveAgentDefinitionsByWorkspace :many
SELECT id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at FROM agent_definition
WHERE workspace_id = ? AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAgentDefinitionsByWorkspace(ctx context.Context, workspaceID string) ([]AgentDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAgentDefinitionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDefinition{}
	for rows.Next() {
		var i AgentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.AgentType,
			&i.Objective,
			&i.AllowedTools,
			&i.Limits,
			&i.TriggerConfig,
			&i.PolicySetID,
			&i.ActivePromptVersionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentDefinitionsByType = `-- name: ListAgentDefinitionsByType :many
SELECT id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at FROM agent_definition
WHERE workspace_id = ? AND agent_type = ?
ORDER BY created_at DESC
`

type ListAgentDefinitionsByTypeParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	AgentType   string `db:"agent_type" json:"agentType"`
}

func (q *Queries) ListAgentDefinitionsByType(ctx context.Context, arg ListAgentDefinitionsByTypeParams) ([]AgentDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listAgentDefinitionsByType, arg.WorkspaceID, arg.AgentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDefinition{}
	for rows.Next() {
		var i AgentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.AgentType,
			&i.Objective,
			&i.AllowedTools,
			&i.Limits,
			&i.TriggerConfig,
			&i.PolicySetID,
			&i.ActivePromptVersionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentDefinitionsByWorkspace = `-- name: ListAgentDefinitionsByWorkspace :many
SELECT id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at FROM agent_definition
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAgentDefinitionsByWorkspace(ctx context.Context, workspaceID string) ([]AgentDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listAgentDefinitionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDefinition{}
	for rows.Next() {
		var i AgentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.AgentType,
			&i.Objective,
			&i.AllowedTools,
			&i.Limits,
			&i.TriggerConfig,
			&i.PolicySetID,
			&i.ActivePromptVersionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsByAgent = `-- name: ListAgentRunsByAgent :many
SELECT id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at FROM agent_run
WHERE workspace_id = ? AND agent_definition_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAgentRunsByAgentParams struct {
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	Limit             int64  `db:"limit" json:"limit"`
	Offset            int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListAgentRunsByAgent(ctx context.Context, arg ListAgentRunsByAgentParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByAgent,
		arg.WorkspaceID,
		arg.AgentDefinitionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.TriggerContext,
			&i.Status,
			&i.Inputs,
			&i.RetrievalQueries,
			&i.RetrievedEvidenceIds,
			&i.ReasoningTrace,
			&i.ToolCalls,
			&i.Output,
			&i.AbstentionReason,
			&i.TotalTokens,
			&i.TotalCost,
			&i.LatencyMs,
			&i.TraceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsByStatus = `-- name: ListAgentRunsByStatus :many
SELECT id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at FROM agent_run
WHERE workspace_id = ? AND status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAgentRunsByStatusParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Status      string `db:"status" json:"status"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListAgentRunsByStatus(ctx context.Context, arg ListAgentRunsByStatusParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByStatus,
		arg.WorkspaceID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.TriggerContext,
			&i.Status,
			&i.Inputs,
			&i.RetrievalQueries,
			&i.RetrievedEvidenceIds,
			&i.ReasoningTrace,
			&i.ToolCalls,
			&i.Output,
			&i.AbstentionReason,
			&i.TotalTokens,
			&i.TotalCost,
			&i.LatencyMs,
			&i.TraceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsByUser = `-- name: ListAgentRunsByUser :many
SELECT id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at FROM agent_run
WHERE workspace_id = ? AND triggered_by_user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAgentRunsByUserParams struct {
	WorkspaceID       string  `db:"workspace_id" json:"workspaceId"`
	TriggeredByUserID *string `db:"triggered_by_user_id" json:"triggeredByUserId"`
	Limit             int64   `db:"limit" json:"limit"`
	Offset            int64   `db:"offset" json:"offset"`
}

func (q *Queries) ListAgentRunsByUser(ctx context.Context, arg ListAgentRunsByUserParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByUser,
		arg.WorkspaceID,
		arg.TriggeredByUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.TriggerContext,
			&i.Status,
			&i.Inputs,
			&i.RetrievalQueries,
			&i.RetrievedEvidenceIds,
			&i.ReasoningTrace,
			&i.ToolCalls,
			&i.Output,
			&i.AbstentionReason,
			&i.TotalTokens,
			&i.TotalCost,
			&i.LatencyMs,
			&i.TraceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunsByWorkspace = `-- name: ListAgentRunsByWorkspace :many
SELECT id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at FROM agent_run
WHERE workspace_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAgentRunsByWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListAgentRunsByWorkspace(ctx context.Context, arg ListAgentRunsByWorkspaceParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.TriggeredByUserID,
			&i.TriggerType,
			&i.TriggerContext,
			&i.Status,
			&i.Inputs,
			&i.RetrievalQueries,
			&i.RetrievedEvidenceIds,
			&i.ReasoningTrace,
			&i.ToolCalls,
			&i.Output,
			&i.AbstentionReason,
			&i.TotalTokens,
			&i.TotalCost,
			&i.LatencyMs,
			&i.TraceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillDefinitionsByAgent = `-- name: ListSkillDefinitionsByAgent :many
SELECT id, workspace_id, name, description, steps, agent_definition_id, status, created_at, updated_at FROM skill_definition
WHERE agent_definition_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSkillDefinitionsByAgent(ctx context.Context, agentDefinitionID *string) ([]SkillDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listSkillDefinitionsByAgent, agentDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillDefinition{}
	for rows.Next() {
		var i SkillDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Steps,
			&i.AgentDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillDefinitionsByWorkspace = `-- name: ListSkillDefinitionsByWorkspace :many
SELECT id, workspace_id, name, description, steps, agent_definition_id, status, created_at, updated_at FROM skill_definition
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSkillDefinitionsByWorkspace(ctx context.Context, workspaceID string) ([]SkillDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listSkillDefinitionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillDefinition{}
	for rows.Next() {
		var i SkillDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Steps,
			&i.AgentDefinitionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentDefinition = `-- name: UpdateAgentDefinition :one
UPDATE agent_definition
SET name = ?, description = ?, agent_type = ?, objective = ?,
    allowed_tools = ?, limits = ?, trigger_config = ?, policy_set_id = ?,
    active_prompt_version_id = ?, status = ?, updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, name, description, agent_type, objective, allowed_tools, limits, trigger_config, policy_set_id, active_prompt_version_id, status, created_at, updated_at
`

type UpdateAgentDefinitionParams struct {
	Name                  string          `db:"name" json:"name"`
	Description           *string         `db:"description" json:"description"`
	AgentType             string          `db:"agent_type" json:"agentType"`
	Objective             json.RawMessage `db:"objective" json:"objective"`
	AllowedTools          json.RawMessage `db:"allowed_tools" json:"allowedTools"`
	Limits                json.RawMessage `db:"limits" json:"limits"`
	TriggerConfig         json.RawMessage `db:"trigger_config" json:"triggerConfig"`
	PolicySetID           *string         `db:"policy_set_id" json:"policySetId"`
	ActivePromptVersionID *string         `db:"active_prompt_version_id" json:"activePromptVersionId"`
	Status                string          `db:"status" json:"status"`
	ID                    string          `db:"id" json:"id"`
	WorkspaceID           string          `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateAgentDefinition(ctx context.Context, arg UpdateAgentDefinitionParams) (AgentDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateAgentDefinition,
		arg.Name,
		arg.Description,
		arg.AgentType,
		arg.Objective,
		arg.AllowedTools,
		arg.Limits,
		arg.TriggerConfig,
		arg.PolicySetID,
		arg.ActivePromptVersionID,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
	)
	var i AgentDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.AgentType,
		&i.Objective,
		&i.AllowedTools,
		&i.Limits,
		&i.TriggerConfig,
		&i.PolicySetID,
		&i.ActivePromptVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentRun = `-- name: UpdateAgentRun :one
UPDATE agent_run
SET status = ?, inputs = ?, retrieval_queries = ?, retrieved_evidence_ids = ?,
    reasoning_trace = ?, tool_calls = ?, output = ?, abstention_reason = ?,
    total_tokens = ?, total_cost = ?, latency_ms = ?,
    completed_at = CASE WHEN ? THEN datetime('now') ELSE completed_at END,
    updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at
`

type UpdateAgentRunParams struct {
	Status               string          `db:"status" json:"status"`
	Inputs               json.RawMessage `db:"inputs" json:"inputs"`
	RetrievalQueries     json.RawMessage `db:"retrieval_queries" json:"retrievalQueries"`
	RetrievedEvidenceIds json.RawMessage `db:"retrieved_evidence_ids" json:"retrievedEvidenceIds"`
	ReasoningTrace       json.RawMessage `db:"reasoning_trace" json:"reasoningTrace"`
	ToolCalls            json.RawMessage `db:"tool_calls" json:"toolCalls"`
	Output               json.RawMessage `db:"output" json:"output"`
	AbstentionReason     *string         `db:"abstention_reason" json:"abstentionReason"`
	TotalTokens          *int64          `db:"total_tokens" json:"totalTokens"`
	TotalCost            *float64        `db:"total_cost" json:"totalCost"`
	LatencyMs            *int64          `db:"latency_ms" json:"latencyMs"`
	CompletedAt          *time.Time      `db:"completed_at" json:"completedAt"`
	ID                   string          `db:"id" json:"id"`
	WorkspaceID          string          `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateAgentRun(ctx context.Context, arg UpdateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, updateAgentRun,
		arg.Status,
		arg.Inputs,
		arg.RetrievalQueries,
		arg.RetrievedEvidenceIds,
		arg.ReasoningTrace,
		arg.ToolCalls,
		arg.Output,
		arg.AbstentionReason,
		arg.TotalTokens,
		arg.TotalCost,
		arg.LatencyMs,
		arg.CompletedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.Status,
		&i.Inputs,
		&i.RetrievalQueries,
		&i.RetrievedEvidenceIds,
		&i.ReasoningTrace,
		&i.ToolCalls,
		&i.Output,
		&i.AbstentionReason,
		&i.TotalTokens,
		&i.TotalCost,
		&i.LatencyMs,
		&i.TraceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAgentRunStatus = `-- name: UpdateAgentRunStatus :one
UPDATE agent_run
SET status = ?, completed_at = datetime('now'), updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, agent_definition_id, triggered_by_user_id, trigger_type, trigger_context, status, inputs, retrieval_queries, retrieved_evidence_ids, reasoning_trace, tool_calls, output, abstention_reason, total_tokens, total_cost, latency_ms, trace_id, started_at, completed_at, created_at
`

type UpdateAgentRunStatusParams struct {
	Status      string `db:"status" json:"status"`
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, updateAgentRunStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.TriggeredByUserID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.Status,
		&i.Inputs,
		&i.RetrievalQueries,
		&i.RetrievedEvidenceIds,
		&i.ReasoningTrace,
		&i.ToolCalls,
		&i.Output,
		&i.AbstentionReason,
		&i.TotalTokens,
		&i.TotalCost,
		&i.LatencyMs,
		&i.TraceID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSkillDefinition = `-- name: UpdateSkillDefinition :one
UPDATE skill_definition
SET name = ?, description = ?, steps = ?, agent_definition_id = ?,
    status = ?, updated_at = datetime('now')
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, name, description, steps, agent_definition_id, status, created_at, updated_at
`

type UpdateSkillDefinitionParams struct {
	Name              string          `db:"name" json:"name"`
	Description       *string         `db:"description" json:"description"`
	Steps             json.RawMessage `db:"steps" json:"steps"`
	AgentDefinitionID *string         `db:"agent_definition_id" json:"agentDefinitionId"`
	Status            string          `db:"status" json:"status"`
	ID                string          `db:"id" json:"id"`
	WorkspaceID       string          `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateSkillDefinition(ctx context.Context, arg UpdateSkillDefinitionParams) (SkillDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateSkillDefinition,
		arg.Name,
		arg.Description,
		arg.Steps,
		arg.AgentDefinitionID,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
	)
	var i SkillDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentDefinitionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
