// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachment.sql

package sqlcgen

import (
	"context"
)

const countAttachmentsByEntity = `-- name: CountAttachmentsByEntity :one
SELECT COUNT(*) FROM attachment
WHERE workspace_id = ?
  AND entity_type = ?
  AND entity_id = ?
`

type CountAttachmentsByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
}

func (q *Queries) CountAttachmentsByEntity(ctx context.Context, arg CountAttachmentsByEntityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsByEntity, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttachmentsByWorkspace = `-- name: CountAttachmentsByWorkspace :one
SELECT COUNT(*) FROM attachment
WHERE workspace_id = ?
`

func (q *Queries) CountAttachmentsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :exec

INSERT INTO attachment (id, workspace_id, entity_type, entity_id, uploader_id, filename, content_type, size_bytes, storage_path, sensitivity, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	EntityID    string  `db:"entity_id" json:"entityId"`
	UploaderID  string  `db:"uploader_id" json:"uploaderId"`
	Filename    string  `db:"filename" json:"filename"`
	ContentType *string `db:"content_type" json:"contentType"`
	SizeBytes   *int64  `db:"size_bytes" json:"sizeBytes"`
	StoragePath string  `db:"storage_path" json:"storagePath"`
	Sensitivity *string `db:"sensitivity" json:"sensitivity"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
}

// SQL queries for attachment table
// Task 1.5: File attachment management queries
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.Sensitivity,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachment
WHERE id = ?
  AND workspace_id = ?
`

type DeleteAttachmentParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.WorkspaceID)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, workspace_id, entity_type, entity_id, uploader_id, filename, content_type, size_bytes, storage_path, sensitivity, metadata, created_at
FROM attachment
WHERE id = ?
  AND workspace_id = ?
LIMIT 1
`

type GetAttachmentByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, arg.ID, arg.WorkspaceID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Sensitivity,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalAttachmentSizeByWorkspace = `-- name: GetTotalAttachmentSizeByWorkspace :one
SELECT COALESCE(SUM(size_bytes), 0) FROM attachment
WHERE workspace_id = ?
`

func (q *Queries) GetTotalAttachmentSizeByWorkspace(ctx context.Context, workspaceID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalAttachmentSizeByWorkspace, workspaceID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listAttachmentsByEntity = `-- name: ListAttachmentsByEntity :many
SELECT id, workspace_id, entity_type, entity_id, uploader_id, filename, content_type, size_bytes, storage_path, sensitivity, metadata, created_at
FROM attachment
WHERE workspace_id = ?
  AND entity_type = ?
  AND entity_id = ?
ORDER BY created_at DESC
`

type ListAttachmentsByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
}

func (q *Queries) ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByEntity, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.UploaderID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.Sensitivity,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByUploader = `-- name: ListAttachmentsByUploader :many
SELECT id, workspace_id, entity_type, entity_id, uploader_id, filename, content_type, size_bytes, storage_path, sensitivity, metadata, created_at
FROM attachment
WHERE workspace_id = ?
  AND uploader_id = ?
ORDER BY created_at DESC
`

type ListAttachmentsByUploaderParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	UploaderID  string `db:"uploader_id" json:"uploaderId"`
}

func (q *Queries) ListAttachmentsByUploader(ctx context.Context, arg ListAttachmentsByUploaderParams) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByUploader, arg.WorkspaceID, arg.UploaderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.UploaderID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.Sensitivity,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByWorkspace = `-- name: ListAttachmentsByWorkspace :many
SELECT id, workspace_id, entity_type, entity_id, uploader_id, filename, content_type, size_bytes, storage_path, sensitivity, metadata, created_at
FROM attachment
WHERE workspace_id = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListAttachmentsByWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListAttachmentsByWorkspace(ctx context.Context, arg ListAttachmentsByWorkspaceParams) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.UploaderID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.Sensitivity,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
