// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"encoding/json"
	"time"
)

type Account struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	Domain      *string `db:"domain" json:"domain"`
	Industry    *string `db:"industry" json:"industry"`
	SizeSegment *string `db:"size_segment" json:"sizeSegment"`
	OwnerID     string  `db:"owner_id" json:"ownerId"`
	Address     *string `db:"address" json:"address"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	DeletedAt   *string `db:"deleted_at" json:"deletedAt"`
}

type Activity struct {
	ID           string  `db:"id" json:"id"`
	WorkspaceID  string  `db:"workspace_id" json:"workspaceId"`
	ActivityType string  `db:"activity_type" json:"activityType"`
	EntityType   string  `db:"entity_type" json:"entityType"`
	EntityID     string  `db:"entity_id" json:"entityId"`
	OwnerID      string  `db:"owner_id" json:"ownerId"`
	AssignedTo   *string `db:"assigned_to" json:"assignedTo"`
	Subject      string  `db:"subject" json:"subject"`
	Body         *string `db:"body" json:"body"`
	Status       string  `db:"status" json:"status"`
	DueAt        *string `db:"due_at" json:"dueAt"`
	CompletedAt  *string `db:"completed_at" json:"completedAt"`
	Metadata     *string `db:"metadata" json:"metadata"`
	CreatedAt    string  `db:"created_at" json:"createdAt"`
	UpdatedAt    string  `db:"updated_at" json:"updatedAt"`
}

type Attachment struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	EntityID    string  `db:"entity_id" json:"entityId"`
	UploaderID  string  `db:"uploader_id" json:"uploaderId"`
	Filename    string  `db:"filename" json:"filename"`
	ContentType *string `db:"content_type" json:"contentType"`
	SizeBytes   *int64  `db:"size_bytes" json:"sizeBytes"`
	StoragePath string  `db:"storage_path" json:"storagePath"`
	Sensitivity *string `db:"sensitivity" json:"sensitivity"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
}

type AuditEvent struct {
	ID                 string          `db:"id" json:"id"`
	WorkspaceID        string          `db:"workspace_id" json:"workspaceId"`
	ActorID            string          `db:"actor_id" json:"actorId"`
	ActorType          string          `db:"actor_type" json:"actorType"`
	Action             string          `db:"action" json:"action"`
	EntityType         *string         `db:"entity_type" json:"entityType"`
	EntityID           *string         `db:"entity_id" json:"entityId"`
	Details            json.RawMessage `db:"details" json:"details"`
	PermissionsChecked json.RawMessage `db:"permissions_checked" json:"permissionsChecked"`
	Outcome            string          `db:"outcome" json:"outcome"`
	TraceID            *string         `db:"trace_id" json:"traceId"`
	IpAddress          *string         `db:"ip_address" json:"ipAddress"`
	UserAgent          *string         `db:"user_agent" json:"userAgent"`
	CreatedAt          time.Time       `db:"created_at" json:"createdAt"`
}

type CaseTicket struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	AccountID   *string `db:"account_id" json:"accountId"`
	ContactID   *string `db:"contact_id" json:"contactId"`
	PipelineID  *string `db:"pipeline_id" json:"pipelineId"`
	StageID     *string `db:"stage_id" json:"stageId"`
	OwnerID     string  `db:"owner_id" json:"ownerId"`
	Subject     string  `db:"subject" json:"subject"`
	Description *string `db:"description" json:"description"`
	Priority    string  `db:"priority" json:"priority"`
	Status      string  `db:"status" json:"status"`
	Channel     *string `db:"channel" json:"channel"`
	SlaConfig   *string `db:"sla_config" json:"slaConfig"`
	SlaDeadline *string `db:"sla_deadline" json:"slaDeadline"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	DeletedAt   *string `db:"deleted_at" json:"deletedAt"`
}

type Contact struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	AccountID   string  `db:"account_id" json:"accountId"`
	FirstName   string  `db:"first_name" json:"firstName"`
	LastName    string  `db:"last_name" json:"lastName"`
	Email       *string `db:"email" json:"email"`
	Phone       *string `db:"phone" json:"phone"`
	Title       *string `db:"title" json:"title"`
	Status      string  `db:"status" json:"status"`
	OwnerID     string  `db:"owner_id" json:"ownerId"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	DeletedAt   *string `db:"deleted_at" json:"deletedAt"`
}

type Deal struct {
	ID            string   `db:"id" json:"id"`
	WorkspaceID   string   `db:"workspace_id" json:"workspaceId"`
	AccountID     string   `db:"account_id" json:"accountId"`
	ContactID     *string  `db:"contact_id" json:"contactId"`
	PipelineID    string   `db:"pipeline_id" json:"pipelineId"`
	StageID       string   `db:"stage_id" json:"stageId"`
	OwnerID       string   `db:"owner_id" json:"ownerId"`
	Title         string   `db:"title" json:"title"`
	Amount        *float64 `db:"amount" json:"amount"`
	Currency      *string  `db:"currency" json:"currency"`
	ExpectedClose *string  `db:"expected_close" json:"expectedClose"`
	Status        string   `db:"status" json:"status"`
	Metadata      *string  `db:"metadata" json:"metadata"`
	CreatedAt     string   `db:"created_at" json:"createdAt"`
	UpdatedAt     string   `db:"updated_at" json:"updatedAt"`
	DeletedAt     *string  `db:"deleted_at" json:"deletedAt"`
}

type EmbeddingDocument struct {
	ID              string     `db:"id" json:"id"`
	KnowledgeItemID string     `db:"knowledge_item_id" json:"knowledgeItemId"`
	WorkspaceID     string     `db:"workspace_id" json:"workspaceId"`
	ChunkIndex      int64      `db:"chunk_index" json:"chunkIndex"`
	ChunkText       string     `db:"chunk_text" json:"chunkText"`
	TokenCount      *int64     `db:"token_count" json:"tokenCount"`
	EmbeddingStatus string     `db:"embedding_status" json:"embeddingStatus"`
	EmbeddedAt      *time.Time `db:"embedded_at" json:"embeddedAt"`
	CreatedAt       time.Time  `db:"created_at" json:"createdAt"`
}

type Evidence struct {
	ID              string    `db:"id" json:"id"`
	KnowledgeItemID string    `db:"knowledge_item_id" json:"knowledgeItemId"`
	WorkspaceID     string    `db:"workspace_id" json:"workspaceId"`
	Method          string    `db:"method" json:"method"`
	Score           float64   `db:"score" json:"score"`
	Snippet         *string   `db:"snippet" json:"snippet"`
	PiiRedacted     bool      `db:"pii_redacted" json:"piiRedacted"`
	Metadata        *string   `db:"metadata" json:"metadata"`
	CreatedAt       time.Time `db:"created_at" json:"createdAt"`
}

type KnowledgeItem struct {
	ID                string     `db:"id" json:"id"`
	WorkspaceID       string     `db:"workspace_id" json:"workspaceId"`
	SourceType        string     `db:"source_type" json:"sourceType"`
	Title             string     `db:"title" json:"title"`
	RawContent        string     `db:"raw_content" json:"rawContent"`
	NormalizedContent *string    `db:"normalized_content" json:"normalizedContent"`
	EntityType        *string    `db:"entity_type" json:"entityType"`
	EntityID          *string    `db:"entity_id" json:"entityId"`
	Metadata          *string    `db:"metadata" json:"metadata"`
	CreatedAt         time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time  `db:"updated_at" json:"updatedAt"`
	DeletedAt         *time.Time `db:"deleted_at" json:"deletedAt"`
}

type Lead struct {
	ID          string   `db:"id" json:"id"`
	WorkspaceID string   `db:"workspace_id" json:"workspaceId"`
	ContactID   *string  `db:"contact_id" json:"contactId"`
	AccountID   *string  `db:"account_id" json:"accountId"`
	Source      *string  `db:"source" json:"source"`
	Status      string   `db:"status" json:"status"`
	OwnerID     string   `db:"owner_id" json:"ownerId"`
	Score       *float64 `db:"score" json:"score"`
	Metadata    *string  `db:"metadata" json:"metadata"`
	CreatedAt   string   `db:"created_at" json:"createdAt"`
	UpdatedAt   string   `db:"updated_at" json:"updatedAt"`
	DeletedAt   *string  `db:"deleted_at" json:"deletedAt"`
}

type Note struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	EntityID    string  `db:"entity_id" json:"entityId"`
	AuthorID    string  `db:"author_id" json:"authorId"`
	Content     string  `db:"content" json:"content"`
	IsInternal  bool    `db:"is_internal" json:"isInternal"`
	Metadata    *string `db:"metadata" json:"metadata"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

type Pipeline struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	Settings    *string `db:"settings" json:"settings"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

type PipelineStage struct {
	ID             string   `db:"id" json:"id"`
	PipelineID     string   `db:"pipeline_id" json:"pipelineId"`
	Name           string   `db:"name" json:"name"`
	Position       int64    `db:"position" json:"position"`
	Probability    *float64 `db:"probability" json:"probability"`
	SlaHours       *int64   `db:"sla_hours" json:"slaHours"`
	RequiredFields *string  `db:"required_fields" json:"requiredFields"`
	CreatedAt      string   `db:"created_at" json:"createdAt"`
	UpdatedAt      string   `db:"updated_at" json:"updatedAt"`
}

type Role struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	Permissions string  `db:"permissions" json:"permissions"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

type TimelineEvent struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	EntityID    string  `db:"entity_id" json:"entityId"`
	ActorID     *string `db:"actor_id" json:"actorId"`
	EventType   string  `db:"event_type" json:"eventType"`
	OldValue    *string `db:"old_value" json:"oldValue"`
	NewValue    *string `db:"new_value" json:"newValue"`
	Context     *string `db:"context" json:"context"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
}

type UserAccount struct {
	ID            string  `db:"id" json:"id"`
	WorkspaceID   string  `db:"workspace_id" json:"workspaceId"`
	ExternalIdpID *string `db:"external_idp_id" json:"externalIdpId"`
	Email         string  `db:"email" json:"email"`
	PasswordHash  *string `db:"password_hash" json:"passwordHash"`
	DisplayName   string  `db:"display_name" json:"displayName"`
	AvatarUrl     *string `db:"avatar_url" json:"avatarUrl"`
	Status        string  `db:"status" json:"status"`
	Preferences   *string `db:"preferences" json:"preferences"`
	CreatedAt     string  `db:"created_at" json:"createdAt"`
	UpdatedAt     string  `db:"updated_at" json:"updatedAt"`
}

type UserRole struct {
	ID        string `db:"id" json:"id"`
	UserID    string `db:"user_id" json:"userId"`
	RoleID    string `db:"role_id" json:"roleId"`
	CreatedAt string `db:"created_at" json:"createdAt"`
}

type VecEmbedding struct {
	ID          string    `db:"id" json:"id"`
	WorkspaceID string    `db:"workspace_id" json:"workspaceId"`
	Embedding   string    `db:"embedding" json:"embedding"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
}

type Workspace struct {
	ID        string  `db:"id" json:"id"`
	Name      string  `db:"name" json:"name"`
	Slug      string  `db:"slug" json:"slug"`
	Settings  *string `db:"settings" json:"settings"`
	CreatedAt string  `db:"created_at" json:"createdAt"`
	UpdatedAt string  `db:"updated_at" json:"updatedAt"`
}
