// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline.sql

package sqlcgen

import (
	"context"
)

const countPipelineStagesByPipeline = `-- name: CountPipelineStagesByPipeline :one
SELECT COUNT(*) FROM pipeline_stage
WHERE pipeline_id = ?
`

func (q *Queries) CountPipelineStagesByPipeline(ctx context.Context, pipelineID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPipelineStagesByPipeline, pipelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPipelinesByWorkspace = `-- name: CountPipelinesByWorkspace :one
SELECT COUNT(*) FROM pipeline
WHERE workspace_id = ?
`

func (q *Queries) CountPipelinesByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPipelinesByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipeline = `-- name: CreatePipeline :exec


INSERT INTO pipeline (id, workspace_id, name, entity_type, settings, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePipelineParams struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	Settings    *string `db:"settings" json:"settings"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

// SQL queries for pipeline and pipeline_stage tables
// Task 1.5: Pipeline management queries
// === PIPELINE QUERIES ===
func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) error {
	_, err := q.db.ExecContext(ctx, createPipeline,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.EntityType,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPipelineStage = `-- name: CreatePipelineStage :exec

INSERT INTO pipeline_stage (id, pipeline_id, name, position, probability, sla_hours, required_fields, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePipelineStageParams struct {
	ID             string   `db:"id" json:"id"`
	PipelineID     string   `db:"pipeline_id" json:"pipelineId"`
	Name           string   `db:"name" json:"name"`
	Position       int64    `db:"position" json:"position"`
	Probability    *float64 `db:"probability" json:"probability"`
	SlaHours       *int64   `db:"sla_hours" json:"slaHours"`
	RequiredFields *string  `db:"required_fields" json:"requiredFields"`
	CreatedAt      string   `db:"created_at" json:"createdAt"`
	UpdatedAt      string   `db:"updated_at" json:"updatedAt"`
}

// === PIPELINE STAGE QUERIES ===
func (q *Queries) CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) error {
	_, err := q.db.ExecContext(ctx, createPipelineStage,
		arg.ID,
		arg.PipelineID,
		arg.Name,
		arg.Position,
		arg.Probability,
		arg.SlaHours,
		arg.RequiredFields,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipeline
WHERE id = ?
  AND workspace_id = ?
`

type DeletePipelineParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeletePipeline(ctx context.Context, arg DeletePipelineParams) error {
	_, err := q.db.ExecContext(ctx, deletePipeline, arg.ID, arg.WorkspaceID)
	return err
}

const deletePipelineStage = `-- name: DeletePipelineStage :exec
DELETE FROM pipeline_stage
WHERE id = ?
`

func (q *Queries) DeletePipelineStage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePipelineStage, id)
	return err
}

const deletePipelineStagesByPipeline = `-- name: DeletePipelineStagesByPipeline :exec
DELETE FROM pipeline_stage
WHERE pipeline_id = ?
`

func (q *Queries) DeletePipelineStagesByPipeline(ctx context.Context, pipelineID string) error {
	_, err := q.db.ExecContext(ctx, deletePipelineStagesByPipeline, pipelineID)
	return err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, workspace_id, name, entity_type, settings, created_at, updated_at
FROM pipeline
WHERE id = ?
  AND workspace_id = ?
LIMIT 1
`

type GetPipelineByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetPipelineByID(ctx context.Context, arg GetPipelineByIDParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipelineByID, arg.ID, arg.WorkspaceID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EntityType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineStageByID = `-- name: GetPipelineStageByID :one
SELECT id, pipeline_id, name, position, probability, sla_hours, required_fields, created_at, updated_at
FROM pipeline_stage
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPipelineStageByID(ctx context.Context, id string) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, getPipelineStageByID, id)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Position,
		&i.Probability,
		&i.SlaHours,
		&i.RequiredFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPipelineStagesByPipeline = `-- name: ListPipelineStagesByPipeline :many
SELECT id, pipeline_id, name, position, probability, sla_hours, required_fields, created_at, updated_at
FROM pipeline_stage
WHERE pipeline_id = ?
ORDER BY position ASC
`

func (q *Queries) ListPipelineStagesByPipeline(ctx context.Context, pipelineID string) ([]PipelineStage, error) {
	rows, err := q.db.QueryContext(ctx, listPipelineStagesByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStage{}
	for rows.Next() {
		var i PipelineStage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Position,
			&i.Probability,
			&i.SlaHours,
			&i.RequiredFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByEntityType = `-- name: ListPipelinesByEntityType :many
SELECT id, workspace_id, name, entity_type, settings, created_at, updated_at
FROM pipeline
WHERE workspace_id = ?
  AND entity_type = ?
ORDER BY name ASC
`

type ListPipelinesByEntityTypeParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
}

func (q *Queries) ListPipelinesByEntityType(ctx context.Context, arg ListPipelinesByEntityTypeParams) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelinesByEntityType, arg.WorkspaceID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EntityType,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByWorkspace = `-- name: ListPipelinesByWorkspace :many
SELECT id, workspace_id, name, entity_type, settings, created_at, updated_at
FROM pipeline
WHERE workspace_id = ?
ORDER BY name ASC
LIMIT ?
OFFSET ?
`

type ListPipelinesByWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListPipelinesByWorkspace(ctx context.Context, arg ListPipelinesByWorkspaceParams) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelinesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EntityType,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :exec
UPDATE pipeline
SET name = ?,
    entity_type = ?,
    settings = ?,
    updated_at = ?
WHERE id = ?
  AND workspace_id = ?
`

type UpdatePipelineParams struct {
	Name        string  `db:"name" json:"name"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	Settings    *string `db:"settings" json:"settings"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) error {
	_, err := q.db.ExecContext(ctx, updatePipeline,
		arg.Name,
		arg.EntityType,
		arg.Settings,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updatePipelineStage = `-- name: UpdatePipelineStage :exec
UPDATE pipeline_stage
SET name = ?,
    position = ?,
    probability = ?,
    sla_hours = ?,
    required_fields = ?,
    updated_at = ?
WHERE id = ?
`

type UpdatePipelineStageParams struct {
	Name           string   `db:"name" json:"name"`
	Position       int64    `db:"position" json:"position"`
	Probability    *float64 `db:"probability" json:"probability"`
	SlaHours       *int64   `db:"sla_hours" json:"slaHours"`
	RequiredFields *string  `db:"required_fields" json:"requiredFields"`
	UpdatedAt      string   `db:"updated_at" json:"updatedAt"`
	ID             string   `db:"id" json:"id"`
}

func (q *Queries) UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineStage,
		arg.Name,
		arg.Position,
		arg.Probability,
		arg.SlaHours,
		arg.RequiredFields,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
