// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt.sql

package sqlcgen

import (
	"context"
)

const archivePreviousActivePrompts = `-- name: ArchivePreviousActivePrompts :exec
UPDATE prompt_version
SET status = 'archived'
WHERE agent_definition_id = ?
  AND workspace_id = ?
  AND status = 'active'
  AND id != ?
`

type ArchivePreviousActivePromptsParams struct {
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
	ID                string `db:"id" json:"id"`
}

func (q *Queries) ArchivePreviousActivePrompts(ctx context.Context, arg ArchivePreviousActivePromptsParams) error {
	_, err := q.db.ExecContext(ctx, archivePreviousActivePrompts, arg.AgentDefinitionID, arg.WorkspaceID, arg.ID)
	return err
}

const createPromptVersion = `-- name: CreatePromptVersion :one

INSERT INTO prompt_version (
    id, workspace_id, agent_definition_id, version_number,
    system_prompt, user_prompt_template, config, status, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, 'draft', ?)
RETURNING id, workspace_id, agent_definition_id, version_number, system_prompt, user_prompt_template, config, status, created_by, created_at
`

type CreatePromptVersionParams struct {
	ID                 string  `db:"id" json:"id"`
	WorkspaceID        string  `db:"workspace_id" json:"workspaceId"`
	AgentDefinitionID  string  `db:"agent_definition_id" json:"agentDefinitionId"`
	VersionNumber      int64   `db:"version_number" json:"versionNumber"`
	SystemPrompt       string  `db:"system_prompt" json:"systemPrompt"`
	UserPromptTemplate *string `db:"user_prompt_template" json:"userPromptTemplate"`
	Config             string  `db:"config" json:"config"`
	CreatedBy          *string `db:"created_by" json:"createdBy"`
}

// Task 3.9: Prompt Versioning queries
func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, createPromptVersion,
		arg.ID,
		arg.WorkspaceID,
		arg.AgentDefinitionID,
		arg.VersionNumber,
		arg.SystemPrompt,
		arg.UserPromptTemplate,
		arg.Config,
		arg.CreatedBy,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.VersionNumber,
		&i.SystemPrompt,
		&i.UserPromptTemplate,
		&i.Config,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePrompt = `-- name: GetActivePrompt :one
SELECT id, workspace_id, agent_definition_id, version_number, system_prompt, user_prompt_template, config, status, created_by, created_at FROM prompt_version
WHERE agent_definition_id = ?
  AND workspace_id = ?
  AND status = 'active'
LIMIT 1
`

type GetActivePromptParams struct {
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetActivePrompt(ctx context.Context, arg GetActivePromptParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getActivePrompt, arg.AgentDefinitionID, arg.WorkspaceID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.VersionNumber,
		&i.SystemPrompt,
		&i.UserPromptTemplate,
		&i.Config,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPromptVersionNumber = `-- name: GetLatestPromptVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) AS max_version
FROM prompt_version
WHERE agent_definition_id = ? AND workspace_id = ?
`

type GetLatestPromptVersionNumberParams struct {
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetLatestPromptVersionNumber(ctx context.Context, arg GetLatestPromptVersionNumberParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestPromptVersionNumber, arg.AgentDefinitionID, arg.WorkspaceID)
	var max_version interface{}
	err := row.Scan(&max_version)
	return max_version, err
}

const getPreviousArchivedPrompt = `-- name: GetPreviousArchivedPrompt :one
SELECT id, workspace_id, agent_definition_id, version_number, system_prompt, user_prompt_template, config, status, created_by, created_at FROM prompt_version
WHERE agent_definition_id = ?
  AND workspace_id = ?
  AND status = 'archived'
ORDER BY version_number DESC
LIMIT 1
`

type GetPreviousArchivedPromptParams struct {
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetPreviousArchivedPrompt(ctx context.Context, arg GetPreviousArchivedPromptParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getPreviousArchivedPrompt, arg.AgentDefinitionID, arg.WorkspaceID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.VersionNumber,
		&i.SystemPrompt,
		&i.UserPromptTemplate,
		&i.Config,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersionByID = `-- name: GetPromptVersionByID :one
SELECT id, workspace_id, agent_definition_id, version_number, system_prompt, user_prompt_template, config, status, created_by, created_at FROM prompt_version
WHERE id = ? AND workspace_id = ?
`

type GetPromptVersionByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetPromptVersionByID(ctx context.Context, arg GetPromptVersionByIDParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getPromptVersionByID, arg.ID, arg.WorkspaceID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.VersionNumber,
		&i.SystemPrompt,
		&i.UserPromptTemplate,
		&i.Config,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersionsByAgent = `-- name: ListPromptVersionsByAgent :many
SELECT id, workspace_id, agent_definition_id, version_number, system_prompt, user_prompt_template, config, status, created_by, created_at FROM prompt_version
WHERE agent_definition_id = ?
  AND workspace_id = ?
ORDER BY version_number DESC
`

type ListPromptVersionsByAgentParams struct {
	AgentDefinitionID string `db:"agent_definition_id" json:"agentDefinitionId"`
	WorkspaceID       string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) ListPromptVersionsByAgent(ctx context.Context, arg ListPromptVersionsByAgentParams) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPromptVersionsByAgent, arg.AgentDefinitionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVersion{}
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.VersionNumber,
			&i.SystemPrompt,
			&i.UserPromptTemplate,
			&i.Config,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPromptStatus = `-- name: SetPromptStatus :exec
UPDATE prompt_version
SET status = ?
WHERE id = ? AND workspace_id = ?
`

type SetPromptStatusParams struct {
	Status      string `db:"status" json:"status"`
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) SetPromptStatus(ctx context.Context, arg SetPromptStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPromptStatus, arg.Status, arg.ID, arg.WorkspaceID)
	return err
}
