// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	// ========================
	// USER ROLE (assignment) queries
	// ========================
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	CountAccountsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountActivitiesByEntity(ctx context.Context, arg CountActivitiesByEntityParams) (int64, error)
	CountActivitiesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountAttachmentsByEntity(ctx context.Context, arg CountAttachmentsByEntityParams) (int64, error)
	CountAttachmentsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountCasesByStatus(ctx context.Context, arg CountCasesByStatusParams) (int64, error)
	CountCasesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountContactsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountDealsByPipeline(ctx context.Context, arg CountDealsByPipelineParams) (int64, error)
	CountDealsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountLeadsByStatus(ctx context.Context, arg CountLeadsByStatusParams) (int64, error)
	CountLeadsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountNotesByEntity(ctx context.Context, arg CountNotesByEntityParams) (int64, error)
	CountNotesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountOverdueCases(ctx context.Context, workspaceID string) (int64, error)
	CountPendingActivitiesByAssignee(ctx context.Context, arg CountPendingActivitiesByAssigneeParams) (int64, error)
	CountPipelineStagesByPipeline(ctx context.Context, pipelineID string) (int64, error)
	CountPipelinesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountTimelineEventsByEntity(ctx context.Context, arg CountTimelineEventsByEntityParams) (int64, error)
	CountTimelineEventsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountUsersByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	// SQL queries for account table
	// Task 1.3.2: sqlc-annotated queries
	// IMPORTANT: All account queries filter by workspace_id for multi-tenancy isolation.
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	// SQL queries for activity table
	// Task 1.5: Activity (tasks, events, calls, emails) management queries
	CreateActivity(ctx context.Context, arg CreateActivityParams) error
	// SQL queries for attachment table
	// Task 1.5: File attachment management queries
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	// SQL queries for case_ticket table
	// Task 1.5: Case/Support ticket management queries
	CreateCase(ctx context.Context, arg CreateCaseParams) error
	// SQL queries for contact table
	// Task 1.4: sqlc-annotated queries
	// IMPORTANT: All contact queries filter by workspace_id for multi-tenancy isolation.
	CreateContact(ctx context.Context, arg CreateContactParams) error
	// SQL queries for deal table
	// Task 1.5: Deal management queries
	CreateDeal(ctx context.Context, arg CreateDealParams) error
	// SQL queries for lead table
	// Task 1.5: Lead management queries
	CreateLead(ctx context.Context, arg CreateLeadParams) error
	// SQL queries for note table
	// Task 1.5: Note/comment management queries
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	// SQL queries for pipeline and pipeline_stage tables
	// Task 1.5: Pipeline management queries
	// === PIPELINE QUERIES ===
	CreatePipeline(ctx context.Context, arg CreatePipelineParams) error
	// === PIPELINE STAGE QUERIES ===
	CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) error
	// SQL queries for role and user_role tables
	// Task 1.2.7: sqlc-annotated queries
	// IMPORTANT: All role queries filter by workspace_id for RBAC isolation.
	// ========================
	// ROLE queries
	// ========================
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// SQL queries for timeline_event table
	// Task 1.5: Timeline/audit trail queries
	CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) error
	// SQL queries for user_account table
	// Task 1.2.7: sqlc-annotated queries
	// IMPORTANT: All user queries filter by workspace_id for multi-tenancy isolation.
	// Note: RETURNING * not supported by sqlc SQLite parser — use :exec + GetByID pattern.
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// SQL queries for workspace table
	// Task 1.2.7: sqlc-annotated queries
	// Note: RETURNING * not supported by sqlc SQLite parser — use :exec + GetByID pattern.
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeletePipeline(ctx context.Context, arg DeletePipelineParams) error
	DeletePipelineStage(ctx context.Context, id string) error
	DeletePipelineStagesByPipeline(ctx context.Context, pipelineID string) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteWorkspace(ctx context.Context, id string) error
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetActivityByID(ctx context.Context, arg GetActivityByIDParams) (Activity, error)
	GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error)
	GetCaseByID(ctx context.Context, arg GetCaseByIDParams) (CaseTicket, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	GetDealByID(ctx context.Context, arg GetDealByIDParams) (Deal, error)
	GetLatestTimelineEventByEntity(ctx context.Context, arg GetLatestTimelineEventByEntityParams) (TimelineEvent, error)
	GetLeadByID(ctx context.Context, arg GetLeadByIDParams) (Lead, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error)
	GetPipelineByID(ctx context.Context, arg GetPipelineByIDParams) (Pipeline, error)
	GetPipelineStageByID(ctx context.Context, id string) (PipelineStage, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetTimelineEventByID(ctx context.Context, arg GetTimelineEventByIDParams) (TimelineEvent, error)
	GetTotalAttachmentSizeByWorkspace(ctx context.Context, workspaceID string) (interface{}, error)
	GetUserByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserByExternalIDP(ctx context.Context, externalIdpID *string) (UserAccount, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (UserAccount, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	ListAccountsByOwner(ctx context.Context, arg ListAccountsByOwnerParams) ([]Account, error)
	ListAccountsByWorkspace(ctx context.Context, arg ListAccountsByWorkspaceParams) ([]Account, error)
	ListActiveUsersByWorkspace(ctx context.Context, workspaceID string) ([]UserAccount, error)
	ListActivitiesByAssignee(ctx context.Context, arg ListActivitiesByAssigneeParams) ([]Activity, error)
	ListActivitiesByEntity(ctx context.Context, arg ListActivitiesByEntityParams) ([]Activity, error)
	ListActivitiesByOwner(ctx context.Context, arg ListActivitiesByOwnerParams) ([]Activity, error)
	ListActivitiesByStatus(ctx context.Context, arg ListActivitiesByStatusParams) ([]Activity, error)
	ListActivitiesByType(ctx context.Context, arg ListActivitiesByTypeParams) ([]Activity, error)
	ListActivitiesByWorkspace(ctx context.Context, arg ListActivitiesByWorkspaceParams) ([]Activity, error)
	ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]Attachment, error)
	ListAttachmentsByUploader(ctx context.Context, arg ListAttachmentsByUploaderParams) ([]Attachment, error)
	ListAttachmentsByWorkspace(ctx context.Context, arg ListAttachmentsByWorkspaceParams) ([]Attachment, error)
	ListCasesByAccount(ctx context.Context, arg ListCasesByAccountParams) ([]CaseTicket, error)
	ListCasesByOwner(ctx context.Context, arg ListCasesByOwnerParams) ([]CaseTicket, error)
	ListCasesBySLADeadline(ctx context.Context, arg ListCasesBySLADeadlineParams) ([]CaseTicket, error)
	ListCasesByStatus(ctx context.Context, arg ListCasesByStatusParams) ([]CaseTicket, error)
	ListCasesByWorkspace(ctx context.Context, arg ListCasesByWorkspaceParams) ([]CaseTicket, error)
	ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error)
	ListContactsByWorkspace(ctx context.Context, arg ListContactsByWorkspaceParams) ([]Contact, error)
	ListDealsByAccount(ctx context.Context, arg ListDealsByAccountParams) ([]Deal, error)
	ListDealsByOwner(ctx context.Context, arg ListDealsByOwnerParams) ([]Deal, error)
	ListDealsByPipeline(ctx context.Context, arg ListDealsByPipelineParams) ([]Deal, error)
	ListDealsByStage(ctx context.Context, arg ListDealsByStageParams) ([]Deal, error)
	ListDealsByStatus(ctx context.Context, arg ListDealsByStatusParams) ([]Deal, error)
	ListDealsByWorkspace(ctx context.Context, arg ListDealsByWorkspaceParams) ([]Deal, error)
	ListLeadsByAccount(ctx context.Context, arg ListLeadsByAccountParams) ([]Lead, error)
	ListLeadsByOwner(ctx context.Context, arg ListLeadsByOwnerParams) ([]Lead, error)
	ListLeadsByStatus(ctx context.Context, arg ListLeadsByStatusParams) ([]Lead, error)
	ListLeadsByWorkspace(ctx context.Context, arg ListLeadsByWorkspaceParams) ([]Lead, error)
	ListNotesByAuthor(ctx context.Context, arg ListNotesByAuthorParams) ([]Note, error)
	ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error)
	ListNotesByEntityPublic(ctx context.Context, arg ListNotesByEntityPublicParams) ([]Note, error)
	ListNotesByWorkspace(ctx context.Context, arg ListNotesByWorkspaceParams) ([]Note, error)
	ListOpenCasesByPriority(ctx context.Context, workspaceID string) ([]CaseTicket, error)
	ListPendingActivitiesByAssignee(ctx context.Context, arg ListPendingActivitiesByAssigneeParams) ([]Activity, error)
	ListPipelineStagesByPipeline(ctx context.Context, pipelineID string) ([]PipelineStage, error)
	ListPipelinesByEntityType(ctx context.Context, arg ListPipelinesByEntityTypeParams) ([]Pipeline, error)
	ListPipelinesByWorkspace(ctx context.Context, arg ListPipelinesByWorkspaceParams) ([]Pipeline, error)
	ListRolesByUser(ctx context.Context, arg ListRolesByUserParams) ([]Role, error)
	ListRolesByWorkspace(ctx context.Context, workspaceID string) ([]Role, error)
	ListTimelineEventsByActor(ctx context.Context, arg ListTimelineEventsByActorParams) ([]TimelineEvent, error)
	ListTimelineEventsByEntity(ctx context.Context, arg ListTimelineEventsByEntityParams) ([]TimelineEvent, error)
	ListTimelineEventsByEventType(ctx context.Context, arg ListTimelineEventsByEventTypeParams) ([]TimelineEvent, error)
	ListTimelineEventsByWorkspace(ctx context.Context, arg ListTimelineEventsByWorkspaceParams) ([]TimelineEvent, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]UserAccount, error)
	ListUsersByWorkspace(ctx context.Context, workspaceID string) ([]UserAccount, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	RevokeAllRoles(ctx context.Context, userID string) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error
	SoftDeleteCase(ctx context.Context, arg SoftDeleteCaseParams) error
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error
	SumDealAmountByPipeline(ctx context.Context, arg SumDealAmountByPipelineParams) (interface{}, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) error
	UpdateCase(ctx context.Context, arg UpdateCaseParams) error
	UpdateContact(ctx context.Context, arg UpdateContactParams) error
	UpdateDeal(ctx context.Context, arg UpdateDealParams) error
	UpdateLead(ctx context.Context, arg UpdateLeadParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) error
	UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error
}

var _ Querier = (*Queries)(nil)
