// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	// ========================
	// USER ROLE (assignment) queries
	// ========================
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	CountAccountsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountActivitiesByEntity(ctx context.Context, arg CountActivitiesByEntityParams) (int64, error)
	CountActivitiesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountAttachmentsByEntity(ctx context.Context, arg CountAttachmentsByEntityParams) (int64, error)
	CountAttachmentsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	// Counts total audit events for a workspace
	CountAuditEventsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountCasesByStatus(ctx context.Context, arg CountCasesByStatusParams) (int64, error)
	CountCasesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountContactsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountDealsByPipeline(ctx context.Context, arg CountDealsByPipelineParams) (int64, error)
	CountDealsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	// Task 2.2: Count total knowledge items for a workspace
	CountKnowledgeItemsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountLeadsByStatus(ctx context.Context, arg CountLeadsByStatusParams) (int64, error)
	CountLeadsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountNotesByEntity(ctx context.Context, arg CountNotesByEntityParams) (int64, error)
	CountNotesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountOverdueCases(ctx context.Context, workspaceID string) (int64, error)
	CountPendingActivitiesByAssignee(ctx context.Context, arg CountPendingActivitiesByAssigneeParams) (int64, error)
	// Task 2.4/2.7: Count pending embeddings for a workspace
	CountPendingEmbeddingsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountPipelineStagesByPipeline(ctx context.Context, pipelineID string) (int64, error)
	CountPipelinesByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountTimelineEventsByEntity(ctx context.Context, arg CountTimelineEventsByEntityParams) (int64, error)
	CountTimelineEventsByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	CountUsersByWorkspace(ctx context.Context, workspaceID string) (int64, error)
	// SQL queries for account table
	// Task 1.3.2: sqlc-annotated queries
	// IMPORTANT: All account queries filter by workspace_id for multi-tenancy isolation.
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	// SQL queries for activity table
	// Task 1.5: Activity (tasks, events, calls, emails) management queries
	CreateActivity(ctx context.Context, arg CreateActivityParams) error
	// SQL queries for attachment table
	// Task 1.5: File attachment management queries
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	// Queries for audit_event table
	// Related to: Task 1.7, internal/domain/audit
	// Creates a new audit event (append-only, immutable)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	// SQL queries for case_ticket table
	// Task 1.5: Case/Support ticket management queries
	CreateCase(ctx context.Context, arg CreateCaseParams) error
	// SQL queries for contact table
	// Task 1.4: sqlc-annotated queries
	// IMPORTANT: All contact queries filter by workspace_id for multi-tenancy isolation.
	CreateContact(ctx context.Context, arg CreateContactParams) error
	// SQL queries for deal table
	// Task 1.5: Deal management queries
	CreateDeal(ctx context.Context, arg CreateDealParams) error
	// ============================================================================
	// EMBEDDING DOCUMENT QUERIES
	// ============================================================================
	// Task 2.2/2.4: Insert a chunk with pending embedding status
	CreateEmbeddingDocument(ctx context.Context, arg CreateEmbeddingDocumentParams) error
	// ============================================================================
	// EVIDENCE QUERIES
	// ============================================================================
	// Task 2.6: Store a search result snapshot
	CreateEvidence(ctx context.Context, arg CreateEvidenceParams) error
	// Queries for knowledge layer tables
	// Related to: Task 2.1, internal/domain/knowledge
	// SECURITY NOTE: All queries include workspace_id filter to enforce multi-tenant isolation.
	// Vector search (vec_embedding) is NOT handled here - modernc.org/sqlite requires
	// raw sql.DB queries for virtual tables. See Task 2.5 for safe vector query patterns.
	// ============================================================================
	// KNOWLEDGE ITEM QUERIES
	// ============================================================================
	// Task 2.1/2.2: Insert a new knowledge item
	CreateKnowledgeItem(ctx context.Context, arg CreateKnowledgeItemParams) error
	// SQL queries for lead table
	// Task 1.5: Lead management queries
	CreateLead(ctx context.Context, arg CreateLeadParams) error
	// SQL queries for note table
	// Task 1.5: Note/comment management queries
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	// SQL queries for pipeline and pipeline_stage tables
	// Task 1.5: Pipeline management queries
	// === PIPELINE QUERIES ===
	CreatePipeline(ctx context.Context, arg CreatePipelineParams) error
	// === PIPELINE STAGE QUERIES ===
	CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) error
	// SQL queries for role and user_role tables
	// Task 1.2.7: sqlc-annotated queries
	// IMPORTANT: All role queries filter by workspace_id for RBAC isolation.
	// ========================
	// ROLE queries
	// ========================
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// SQL queries for timeline_event table
	// Task 1.5: Timeline/audit trail queries
	CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) error
	// SQL queries for user_account table
	// Task 1.2.7: sqlc-annotated queries
	// IMPORTANT: All user queries filter by workspace_id for multi-tenancy isolation.
	// Note: RETURNING * not supported by sqlc SQLite parser — use :exec + GetByID pattern.
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// SQL queries for workspace table
	// Task 1.2.7: sqlc-annotated queries
	// Note: RETURNING * not supported by sqlc SQLite parser — use :exec + GetByID pattern.
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error
	// Task 2.7: Remove all chunks when knowledge item is deleted/reindexed
	DeleteEmbeddingDocumentsByKnowledgeItem(ctx context.Context, arg DeleteEmbeddingDocumentsByKnowledgeItemParams) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeletePipeline(ctx context.Context, arg DeletePipelineParams) error
	DeletePipelineStage(ctx context.Context, id string) error
	DeletePipelineStagesByPipeline(ctx context.Context, pipelineID string) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	// Task 2.4: Remove vectors for all chunks of a knowledge_item (on re-ingest).
	DeleteVecEmbeddingsByKnowledgeItem(ctx context.Context, arg DeleteVecEmbeddingsByKnowledgeItemParams) error
	DeleteWorkspace(ctx context.Context, id string) error
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetActivityByID(ctx context.Context, arg GetActivityByIDParams) (Activity, error)
	// ============================================================================
	// search queries (Task 2.5)
	// ============================================================================
	// Task 2.5: Fetches all embedded vectors for a workspace for in-memory cosine
	// distance calculation. workspace_id filter via JOIN (multi-tenant security).
	// Note: BM25/FTS5 query (SearchKnowledgeItemFTS) is executed as raw SQL in
	// search.go because sqlc does not support CREATE VIRTUAL TABLE fts5 syntax.
	GetAllEmbeddedVectorsByWorkspace(ctx context.Context, workspaceID string) ([]GetAllEmbeddedVectorsByWorkspaceRow, error)
	GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error)
	// Retrieves a single audit event by ID
	GetAuditEventByID(ctx context.Context, id string) (AuditEvent, error)
	GetCaseByID(ctx context.Context, arg GetCaseByIDParams) (CaseTicket, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	GetDealByID(ctx context.Context, arg GetDealByIDParams) (Deal, error)
	// Task 2.4: Get a single embedding document
	GetEmbeddingDocumentByID(ctx context.Context, arg GetEmbeddingDocumentByIDParams) (EmbeddingDocument, error)
	// Task 2.6: Retrieve a single evidence record
	GetEvidenceByID(ctx context.Context, arg GetEvidenceByIDParams) (Evidence, error)
	// Task 2.7: Find knowledge item linked to a CRM entity
	GetKnowledgeItemByEntity(ctx context.Context, arg GetKnowledgeItemByEntityParams) (KnowledgeItem, error)
	// Task 2.1/2.2: Retrieve a single knowledge item (excludes soft-deleted)
	GetKnowledgeItemByID(ctx context.Context, arg GetKnowledgeItemByIDParams) (KnowledgeItem, error)
	GetLatestTimelineEventByEntity(ctx context.Context, arg GetLatestTimelineEventByEntityParams) (TimelineEvent, error)
	GetLeadByID(ctx context.Context, arg GetLeadByIDParams) (Lead, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error)
	GetPipelineByID(ctx context.Context, arg GetPipelineByIDParams) (Pipeline, error)
	GetPipelineStageByID(ctx context.Context, id string) (PipelineStage, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetTimelineEventByID(ctx context.Context, arg GetTimelineEventByIDParams) (TimelineEvent, error)
	GetTotalAttachmentSizeByWorkspace(ctx context.Context, workspaceID string) (interface{}, error)
	GetUserByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserByExternalIDP(ctx context.Context, externalIdpID *string) (UserAccount, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (UserAccount, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	// ============================================================================
	// vec_embedding queries (Task 2.4)
	// ============================================================================
	// Task 2.4: Store a float32 vector as JSON TEXT for an embedding_document chunk.
	InsertVecEmbedding(ctx context.Context, arg InsertVecEmbeddingParams) error
	ListAccountsByOwner(ctx context.Context, arg ListAccountsByOwnerParams) ([]Account, error)
	ListAccountsByWorkspace(ctx context.Context, arg ListAccountsByWorkspaceParams) ([]Account, error)
	ListActiveUsersByWorkspace(ctx context.Context, workspaceID string) ([]UserAccount, error)
	ListActivitiesByAssignee(ctx context.Context, arg ListActivitiesByAssigneeParams) ([]Activity, error)
	ListActivitiesByEntity(ctx context.Context, arg ListActivitiesByEntityParams) ([]Activity, error)
	ListActivitiesByOwner(ctx context.Context, arg ListActivitiesByOwnerParams) ([]Activity, error)
	ListActivitiesByStatus(ctx context.Context, arg ListActivitiesByStatusParams) ([]Activity, error)
	ListActivitiesByType(ctx context.Context, arg ListActivitiesByTypeParams) ([]Activity, error)
	ListActivitiesByWorkspace(ctx context.Context, arg ListActivitiesByWorkspaceParams) ([]Activity, error)
	ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]Attachment, error)
	ListAttachmentsByUploader(ctx context.Context, arg ListAttachmentsByUploaderParams) ([]Attachment, error)
	ListAttachmentsByWorkspace(ctx context.Context, arg ListAttachmentsByWorkspaceParams) ([]Attachment, error)
	// Lists audit events filtered by action type
	ListAuditEventsByAction(ctx context.Context, arg ListAuditEventsByActionParams) ([]AuditEvent, error)
	// Lists audit events for a specific actor
	ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditEvent, error)
	// Lists audit events for a specific entity
	ListAuditEventsByEntity(ctx context.Context, arg ListAuditEventsByEntityParams) ([]AuditEvent, error)
	// Lists audit events filtered by outcome (success/denied/error)
	ListAuditEventsByOutcome(ctx context.Context, arg ListAuditEventsByOutcomeParams) ([]AuditEvent, error)
	// Lists audit events within a time range
	ListAuditEventsByTimeRange(ctx context.Context, arg ListAuditEventsByTimeRangeParams) ([]AuditEvent, error)
	// Lists audit events for a workspace with pagination
	// Results ordered by created_at DESC (newest first)
	ListAuditEventsByWorkspace(ctx context.Context, arg ListAuditEventsByWorkspaceParams) ([]AuditEvent, error)
	ListCasesByAccount(ctx context.Context, arg ListCasesByAccountParams) ([]CaseTicket, error)
	ListCasesByOwner(ctx context.Context, arg ListCasesByOwnerParams) ([]CaseTicket, error)
	ListCasesBySLADeadline(ctx context.Context, arg ListCasesBySLADeadlineParams) ([]CaseTicket, error)
	ListCasesByStatus(ctx context.Context, arg ListCasesByStatusParams) ([]CaseTicket, error)
	ListCasesByWorkspace(ctx context.Context, arg ListCasesByWorkspaceParams) ([]CaseTicket, error)
	ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error)
	ListContactsByWorkspace(ctx context.Context, arg ListContactsByWorkspaceParams) ([]Contact, error)
	ListDealsByAccount(ctx context.Context, arg ListDealsByAccountParams) ([]Deal, error)
	ListDealsByOwner(ctx context.Context, arg ListDealsByOwnerParams) ([]Deal, error)
	ListDealsByPipeline(ctx context.Context, arg ListDealsByPipelineParams) ([]Deal, error)
	ListDealsByStage(ctx context.Context, arg ListDealsByStageParams) ([]Deal, error)
	ListDealsByStatus(ctx context.Context, arg ListDealsByStatusParams) ([]Deal, error)
	ListDealsByWorkspace(ctx context.Context, arg ListDealsByWorkspaceParams) ([]Deal, error)
	// Task 2.4: Get all chunks for a knowledge item (for embedding job)
	ListEmbeddingDocumentsByKnowledgeItem(ctx context.Context, arg ListEmbeddingDocumentsByKnowledgeItemParams) ([]EmbeddingDocument, error)
	// Task 2.6: List evidence for a knowledge item, ordered by score
	ListEvidenceByKnowledgeItem(ctx context.Context, arg ListEvidenceByKnowledgeItemParams) ([]Evidence, error)
	// Task 2.6: List evidence filtered by search method
	ListEvidenceByMethod(ctx context.Context, arg ListEvidenceByMethodParams) ([]Evidence, error)
	// Task 2.7: List knowledge items linked to a specific entity type
	ListKnowledgeItemsByEntity(ctx context.Context, arg ListKnowledgeItemsByEntityParams) ([]KnowledgeItem, error)
	// Task 2.2: List all knowledge items for a workspace (paginated)
	ListKnowledgeItemsByWorkspace(ctx context.Context, arg ListKnowledgeItemsByWorkspaceParams) ([]KnowledgeItem, error)
	ListLeadsByAccount(ctx context.Context, arg ListLeadsByAccountParams) ([]Lead, error)
	ListLeadsByOwner(ctx context.Context, arg ListLeadsByOwnerParams) ([]Lead, error)
	ListLeadsByStatus(ctx context.Context, arg ListLeadsByStatusParams) ([]Lead, error)
	ListLeadsByWorkspace(ctx context.Context, arg ListLeadsByWorkspaceParams) ([]Lead, error)
	ListNotesByAuthor(ctx context.Context, arg ListNotesByAuthorParams) ([]Note, error)
	ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error)
	ListNotesByEntityPublic(ctx context.Context, arg ListNotesByEntityPublicParams) ([]Note, error)
	ListNotesByWorkspace(ctx context.Context, arg ListNotesByWorkspaceParams) ([]Note, error)
	ListOpenCasesByPriority(ctx context.Context, workspaceID string) ([]CaseTicket, error)
	ListPendingActivitiesByAssignee(ctx context.Context, arg ListPendingActivitiesByAssigneeParams) ([]Activity, error)
	// Task 2.4: Get all chunks waiting to be embedded (for background job)
	ListPendingEmbeddingsByWorkspace(ctx context.Context, arg ListPendingEmbeddingsByWorkspaceParams) ([]EmbeddingDocument, error)
	ListPipelineStagesByPipeline(ctx context.Context, pipelineID string) ([]PipelineStage, error)
	ListPipelinesByEntityType(ctx context.Context, arg ListPipelinesByEntityTypeParams) ([]Pipeline, error)
	ListPipelinesByWorkspace(ctx context.Context, arg ListPipelinesByWorkspaceParams) ([]Pipeline, error)
	ListRolesByUser(ctx context.Context, arg ListRolesByUserParams) ([]Role, error)
	ListRolesByWorkspace(ctx context.Context, workspaceID string) ([]Role, error)
	ListTimelineEventsByActor(ctx context.Context, arg ListTimelineEventsByActorParams) ([]TimelineEvent, error)
	ListTimelineEventsByEntity(ctx context.Context, arg ListTimelineEventsByEntityParams) ([]TimelineEvent, error)
	ListTimelineEventsByEventType(ctx context.Context, arg ListTimelineEventsByEventTypeParams) ([]TimelineEvent, error)
	ListTimelineEventsByWorkspace(ctx context.Context, arg ListTimelineEventsByWorkspaceParams) ([]TimelineEvent, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]UserAccount, error)
	ListUsersByWorkspace(ctx context.Context, workspaceID string) ([]UserAccount, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	RevokeAllRoles(ctx context.Context, userID string) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error
	SoftDeleteCase(ctx context.Context, arg SoftDeleteCaseParams) error
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error
	// Task 2.2/2.7: Soft delete a knowledge item (preserves audit trail)
	SoftDeleteKnowledgeItem(ctx context.Context, arg SoftDeleteKnowledgeItemParams) error
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error
	SumDealAmountByPipeline(ctx context.Context, arg SumDealAmountByPipelineParams) (interface{}, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) error
	UpdateCase(ctx context.Context, arg UpdateCaseParams) error
	UpdateContact(ctx context.Context, arg UpdateContactParams) error
	UpdateDeal(ctx context.Context, arg UpdateDealParams) error
	// Task 2.4: Mark a chunk as embedded (or failed)
	UpdateEmbeddingDocumentStatus(ctx context.Context, arg UpdateEmbeddingDocumentStatusParams) error
	// Task 2.7: Update normalized content after CDC reindex
	// Triggers knowledge_item_au which re-syncs FTS5 index
	UpdateKnowledgeItemNormalizedContent(ctx context.Context, arg UpdateKnowledgeItemNormalizedContentParams) error
	UpdateLead(ctx context.Context, arg UpdateLeadParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) error
	UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error
}

var _ Querier = (*Queries)(nil)
