// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reports.sql

package sqlcgen

import (
	"context"
)

const caseBacklogByWorkspace = `-- name: CaseBacklogByWorkspace :many
SELECT
    id,
    priority,
    status,
    created_at,
    CAST(julianday('now') - julianday(created_at) AS INTEGER) AS aging_days
FROM case_ticket
WHERE workspace_id = ?
  AND status IN ('open', 'in_progress', 'waiting', 'escalated')
  AND deleted_at IS NULL
  AND (julianday('now') - julianday(created_at)) > (?2 + 0)
ORDER BY created_at ASC
`

type CaseBacklogByWorkspaceParams struct {
	WorkspaceID string      `db:"workspace_id" json:"workspaceId"`
	AgingDays   interface{} `db:"aging_days" json:"agingDays"`
}

type CaseBacklogByWorkspaceRow struct {
	ID        string `db:"id" json:"id"`
	Priority  string `db:"priority" json:"priority"`
	Status    string `db:"status" json:"status"`
	CreatedAt string `db:"created_at" json:"createdAt"`
	AgingDays int64  `db:"aging_days" json:"agingDays"`
}

func (q *Queries) CaseBacklogByWorkspace(ctx context.Context, arg CaseBacklogByWorkspaceParams) ([]CaseBacklogByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, caseBacklogByWorkspace, arg.WorkspaceID, arg.AgingDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseBacklogByWorkspaceRow{}
	for rows.Next() {
		var i CaseBacklogByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.AgingDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseMTTRByWorkspace = `-- name: CaseMTTRByWorkspace :many
SELECT
    priority,
    AVG(julianday(updated_at) - julianday(created_at)) AS avg_resolution_days
FROM case_ticket
WHERE workspace_id = ?
  AND status IN ('closed', 'resolved')
  AND deleted_at IS NULL
GROUP BY priority
`

type CaseMTTRByWorkspaceRow struct {
	Priority          string   `db:"priority" json:"priority"`
	AvgResolutionDays *float64 `db:"avg_resolution_days" json:"avgResolutionDays"`
}

func (q *Queries) CaseMTTRByWorkspace(ctx context.Context, workspaceID string) ([]CaseMTTRByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, caseMTTRByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseMTTRByWorkspaceRow{}
	for rows.Next() {
		var i CaseMTTRByWorkspaceRow
		if err := rows.Scan(&i.Priority, &i.AvgResolutionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseVolumeByWorkspace = `-- name: CaseVolumeByWorkspace :many
SELECT
    priority,
    status,
    COUNT(*) AS count
FROM case_ticket
WHERE workspace_id = ?
  AND deleted_at IS NULL
GROUP BY priority, status
`

type CaseVolumeByWorkspaceRow struct {
	Priority string `db:"priority" json:"priority"`
	Status   string `db:"status" json:"status"`
	Count    int64  `db:"count" json:"count"`
}

func (q *Queries) CaseVolumeByWorkspace(ctx context.Context, workspaceID string) ([]CaseVolumeByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, caseVolumeByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseVolumeByWorkspaceRow{}
	for rows.Next() {
		var i CaseVolumeByWorkspaceRow
		if err := rows.Scan(&i.Priority, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dealAgingByWorkspace = `-- name: DealAgingByWorkspace :many
SELECT
    ps.name,
    AVG(julianday('now') - julianday(d.updated_at)) AS avg_days
FROM deal d
JOIN pipeline_stage ps ON d.stage_id = ps.id
WHERE d.workspace_id = ?
  AND d.status = 'open'
  AND d.deleted_at IS NULL
GROUP BY ps.id
`

type DealAgingByWorkspaceRow struct {
	Name    string   `db:"name" json:"name"`
	AvgDays *float64 `db:"avg_days" json:"avgDays"`
}

func (q *Queries) DealAgingByWorkspace(ctx context.Context, workspaceID string) ([]DealAgingByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, dealAgingByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealAgingByWorkspaceRow{}
	for rows.Next() {
		var i DealAgingByWorkspaceRow
		if err := rows.Scan(&i.Name, &i.AvgDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesFunnelByWorkspace = `-- name: SalesFunnelByWorkspace :many

SELECT
    ps.name,
    ps.position AS stage_order,
    COUNT(d.id) AS deal_count,
    COALESCE(SUM(d.amount), 0) AS total_value,
    COALESCE(ps.probability, 0) AS probability
FROM pipeline_stage ps
JOIN pipeline p ON p.id = ps.pipeline_id
LEFT JOIN deal d ON d.stage_id = ps.id
    AND d.workspace_id = p.workspace_id
    AND d.deleted_at IS NULL
WHERE p.workspace_id = ?
  AND p.entity_type = 'deal'
GROUP BY ps.id
ORDER BY ps.position
`

type SalesFunnelByWorkspaceRow struct {
	Name        string      `db:"name" json:"name"`
	StageOrder  int64       `db:"stage_order" json:"stageOrder"`
	DealCount   int64       `db:"deal_count" json:"dealCount"`
	TotalValue  interface{} `db:"total_value" json:"totalValue"`
	Probability float64     `db:"probability" json:"probability"`
}

// Task 4.5e - Reporting base queries (FR-003)
func (q *Queries) SalesFunnelByWorkspace(ctx context.Context, workspaceID string) ([]SalesFunnelByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, salesFunnelByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesFunnelByWorkspaceRow{}
	for rows.Next() {
		var i SalesFunnelByWorkspaceRow
		if err := rows.Scan(
			&i.Name,
			&i.StageOrder,
			&i.DealCount,
			&i.TotalValue,
			&i.Probability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
