// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package sqlcgen

import (
	"context"
)

const assignRole = `-- name: AssignRole :exec

INSERT INTO user_role (id, user_id, role_id, created_at)
VALUES (?, ?, ?, ?)
`

type AssignRoleParams struct {
	ID        string `db:"id" json:"id"`
	UserID    string `db:"user_id" json:"userId"`
	RoleID    string `db:"role_id" json:"roleId"`
	CreatedAt string `db:"created_at" json:"createdAt"`
}

// ========================
// USER ROLE (assignment) queries
// ========================
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignRole,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.CreatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec


INSERT INTO role (id, workspace_id, name, description, permissions, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	Permissions string  `db:"permissions" json:"permissions"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
}

// SQL queries for role and user_role tables
// Task 1.2.7: sqlc-annotated queries
// IMPORTANT: All role queries filter by workspace_id for RBAC isolation.
// ========================
// ROLE queries
// ========================
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM role
WHERE id = ?
  AND workspace_id = ?
`

type DeleteRoleParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRole, arg.ID, arg.WorkspaceID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, workspace_id, name, description, permissions, created_at, updated_at
FROM role
WHERE id = ?
  AND workspace_id = ?
LIMIT 1
`

type GetRoleByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, arg.ID, arg.WorkspaceID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, workspace_id, name, description, permissions, created_at, updated_at
FROM role
WHERE workspace_id = ?
  AND name = ?
LIMIT 1
`

type GetRoleByNameParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Name        string `db:"name" json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, arg.WorkspaceID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT id, user_id, role_id, created_at
FROM user_role
WHERE user_id = ?
  AND role_id = ?
LIMIT 1
`

type GetUserRoleParams struct {
	UserID string `db:"user_id" json:"userId"`
	RoleID string `db:"role_id" json:"roleId"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
	)
	return i, err
}

const listRolesByUser = `-- name: ListRolesByUser :many
SELECT r.id, r.workspace_id, r.name, r.description, r.permissions, r.created_at, r.updated_at
FROM role r
JOIN user_role ur ON ur.role_id = r.id
WHERE ur.user_id = ?
  AND r.workspace_id = ?
ORDER BY r.name ASC
`

type ListRolesByUserParams struct {
	UserID      string `db:"user_id" json:"userId"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) ListRolesByUser(ctx context.Context, arg ListRolesByUserParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByUser, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByWorkspace = `-- name: ListRolesByWorkspace :many
SELECT id, workspace_id, name, description, permissions, created_at, updated_at
FROM role
WHERE workspace_id = ?
ORDER BY name ASC
`

func (q *Queries) ListRolesByWorkspace(ctx context.Context, workspaceID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT ua.id, ua.workspace_id, ua.external_idp_id, ua.email, ua.password_hash, ua.display_name, ua.avatar_url, ua.status, ua.preferences, ua.created_at, ua.updated_at
FROM user_account ua
JOIN user_role ur ON ur.user_id = ua.id
WHERE ur.role_id = ?
  AND ua.workspace_id = ?
ORDER BY ua.display_name ASC
`

type ListUsersByRoleParams struct {
	RoleID      string `db:"role_id" json:"roleId"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]UserAccount, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRole, arg.RoleID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAccount{}
	for rows.Next() {
		var i UserAccount
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ExternalIdpID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRoles = `-- name: RevokeAllRoles :exec
DELETE FROM user_role
WHERE user_id = ?
`

func (q *Queries) RevokeAllRoles(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllRoles, userID)
	return err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_role
WHERE user_id = ?
  AND role_id = ?
`

type RevokeRoleParams struct {
	UserID string `db:"user_id" json:"userId"`
	RoleID string `db:"role_id" json:"roleId"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokeRole, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE role
SET name        = ?,
    description = ?,
    permissions = ?,
    updated_at  = ?
WHERE id = ?
  AND workspace_id = ?
`

type UpdateRoleParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	Permissions string  `db:"permissions" json:"permissions"`
	UpdatedAt   string  `db:"updated_at" json:"updatedAt"`
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
