// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signal.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const createSignal = `-- name: CreateSignal :one

INSERT INTO signal (
    id, workspace_id, entity_type, entity_id, signal_type, confidence,
    evidence_ids, source_type, source_id, metadata, status, dismissed_by,
    dismissed_at, expires_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at
`

type CreateSignalParams struct {
	ID          string          `db:"id" json:"id"`
	WorkspaceID string          `db:"workspace_id" json:"workspaceId"`
	EntityType  string          `db:"entity_type" json:"entityType"`
	EntityID    string          `db:"entity_id" json:"entityId"`
	SignalType  string          `db:"signal_type" json:"signalType"`
	Confidence  float64         `db:"confidence" json:"confidence"`
	EvidenceIds json.RawMessage `db:"evidence_ids" json:"evidenceIds"`
	SourceType  string          `db:"source_type" json:"sourceType"`
	SourceID    string          `db:"source_id" json:"sourceId"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata"`
	Status      string          `db:"status" json:"status"`
	DismissedBy *string         `db:"dismissed_by" json:"dismissedBy"`
	DismissedAt *time.Time      `db:"dismissed_at" json:"dismissedAt"`
	ExpiresAt   *time.Time      `db:"expires_at" json:"expiresAt"`
	CreatedAt   time.Time       `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updatedAt"`
}

// AGENT_SPEC Phase 2: Signal foundation queries
func (q *Queries) CreateSignal(ctx context.Context, arg CreateSignalParams) (Signal, error) {
	row := q.db.QueryRowContext(ctx, createSignal,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.SignalType,
		arg.Confidence,
		arg.EvidenceIds,
		arg.SourceType,
		arg.SourceID,
		arg.Metadata,
		arg.Status,
		arg.DismissedBy,
		arg.DismissedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.SignalType,
		&i.Confidence,
		&i.EvidenceIds,
		&i.SourceType,
		&i.SourceID,
		&i.Metadata,
		&i.Status,
		&i.DismissedBy,
		&i.DismissedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dismissSignal = `-- name: DismissSignal :one
UPDATE signal
SET status = 'dismissed', dismissed_by = ?, dismissed_at = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at
`

type DismissSignalParams struct {
	DismissedBy *string    `db:"dismissed_by" json:"dismissedBy"`
	DismissedAt *time.Time `db:"dismissed_at" json:"dismissedAt"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updatedAt"`
	ID          string     `db:"id" json:"id"`
	WorkspaceID string     `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DismissSignal(ctx context.Context, arg DismissSignalParams) (Signal, error) {
	row := q.db.QueryRowContext(ctx, dismissSignal,
		arg.DismissedBy,
		arg.DismissedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.SignalType,
		&i.Confidence,
		&i.EvidenceIds,
		&i.SourceType,
		&i.SourceID,
		&i.Metadata,
		&i.Status,
		&i.DismissedBy,
		&i.DismissedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignalByID = `-- name: GetSignalByID :one
SELECT id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at FROM signal
WHERE id = ? AND workspace_id = ?
LIMIT 1
`

type GetSignalByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetSignalByID(ctx context.Context, arg GetSignalByIDParams) (Signal, error) {
	row := q.db.QueryRowContext(ctx, getSignalByID, arg.ID, arg.WorkspaceID)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.SignalType,
		&i.Confidence,
		&i.EvidenceIds,
		&i.SourceType,
		&i.SourceID,
		&i.Metadata,
		&i.Status,
		&i.DismissedBy,
		&i.DismissedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSignalsByEntity = `-- name: ListSignalsByEntity :many
SELECT id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at FROM signal
WHERE workspace_id = ? AND entity_type = ? AND entity_id = ?
ORDER BY created_at DESC
`

type ListSignalsByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
}

func (q *Queries) ListSignalsByEntity(ctx context.Context, arg ListSignalsByEntityParams) ([]Signal, error) {
	rows, err := q.db.QueryContext(ctx, listSignalsByEntity, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.SignalType,
			&i.Confidence,
			&i.EvidenceIds,
			&i.SourceType,
			&i.SourceID,
			&i.Metadata,
			&i.Status,
			&i.DismissedBy,
			&i.DismissedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalsByStatus = `-- name: ListSignalsByStatus :many
SELECT id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at FROM signal
WHERE workspace_id = ? AND status = ?
ORDER BY created_at DESC
`

type ListSignalsByStatusParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Status      string `db:"status" json:"status"`
}

func (q *Queries) ListSignalsByStatus(ctx context.Context, arg ListSignalsByStatusParams) ([]Signal, error) {
	rows, err := q.db.QueryContext(ctx, listSignalsByStatus, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.SignalType,
			&i.Confidence,
			&i.EvidenceIds,
			&i.SourceType,
			&i.SourceID,
			&i.Metadata,
			&i.Status,
			&i.DismissedBy,
			&i.DismissedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalsByWorkspace = `-- name: ListSignalsByWorkspace :many
SELECT id, workspace_id, entity_type, entity_id, signal_type, confidence, evidence_ids, source_type, source_id, metadata, status, dismissed_by, dismissed_at, expires_at, created_at, updated_at FROM signal
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSignalsByWorkspace(ctx context.Context, workspaceID string) ([]Signal, error) {
	rows, err := q.db.QueryContext(ctx, listSignalsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.SignalType,
			&i.Confidence,
			&i.EvidenceIds,
			&i.SourceType,
			&i.SourceID,
			&i.Metadata,
			&i.Status,
			&i.DismissedBy,
			&i.DismissedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
