// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeline.sql

package sqlcgen

import (
	"context"
)

const countTimelineEventsByEntity = `-- name: CountTimelineEventsByEntity :one
SELECT COUNT(*) FROM timeline_event
WHERE workspace_id = ?
  AND entity_type = ?
  AND entity_id = ?
`

type CountTimelineEventsByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
}

func (q *Queries) CountTimelineEventsByEntity(ctx context.Context, arg CountTimelineEventsByEntityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTimelineEventsByEntity, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTimelineEventsByWorkspace = `-- name: CountTimelineEventsByWorkspace :one
SELECT COUNT(*) FROM timeline_event
WHERE workspace_id = ?
`

func (q *Queries) CountTimelineEventsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTimelineEventsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTimelineEvent = `-- name: CreateTimelineEvent :exec

INSERT INTO timeline_event (id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTimelineEventParams struct {
	ID          string  `db:"id" json:"id"`
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	EntityType  string  `db:"entity_type" json:"entityType"`
	EntityID    string  `db:"entity_id" json:"entityId"`
	ActorID     *string `db:"actor_id" json:"actorId"`
	EventType   string  `db:"event_type" json:"eventType"`
	OldValue    *string `db:"old_value" json:"oldValue"`
	NewValue    *string `db:"new_value" json:"newValue"`
	Context     *string `db:"context" json:"context"`
	CreatedAt   string  `db:"created_at" json:"createdAt"`
}

// SQL queries for timeline_event table
// Task 1.5: Timeline/audit trail queries
func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) error {
	_, err := q.db.ExecContext(ctx, createTimelineEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.Context,
		arg.CreatedAt,
	)
	return err
}

const getLatestTimelineEventByEntity = `-- name: GetLatestTimelineEventByEntity :one
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE workspace_id = ?
  AND entity_type = ?
  AND entity_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestTimelineEventByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
}

func (q *Queries) GetLatestTimelineEventByEntity(ctx context.Context, arg GetLatestTimelineEventByEntityParams) (TimelineEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestTimelineEventByEntity, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.ActorID,
		&i.EventType,
		&i.OldValue,
		&i.NewValue,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const getTimelineEventByID = `-- name: GetTimelineEventByID :one
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE id = ?
  AND workspace_id = ?
LIMIT 1
`

type GetTimelineEventByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetTimelineEventByID(ctx context.Context, arg GetTimelineEventByIDParams) (TimelineEvent, error) {
	row := q.db.QueryRowContext(ctx, getTimelineEventByID, arg.ID, arg.WorkspaceID)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.ActorID,
		&i.EventType,
		&i.OldValue,
		&i.NewValue,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const listTimelineEventsByActor = `-- name: ListTimelineEventsByActor :many
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE workspace_id = ?
  AND actor_id = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListTimelineEventsByActorParams struct {
	WorkspaceID string  `db:"workspace_id" json:"workspaceId"`
	ActorID     *string `db:"actor_id" json:"actorId"`
	Limit       int64   `db:"limit" json:"limit"`
	Offset      int64   `db:"offset" json:"offset"`
}

func (q *Queries) ListTimelineEventsByActor(ctx context.Context, arg ListTimelineEventsByActorParams) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByActor,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEventsByEntity = `-- name: ListTimelineEventsByEntity :many
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE workspace_id = ?
  AND entity_type = ?
  AND entity_id = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListTimelineEventsByEntityParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EntityType  string `db:"entity_type" json:"entityType"`
	EntityID    string `db:"entity_id" json:"entityId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListTimelineEventsByEntity(ctx context.Context, arg ListTimelineEventsByEntityParams) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByEntity,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEventsByEventType = `-- name: ListTimelineEventsByEventType :many
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE workspace_id = ?
  AND event_type = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListTimelineEventsByEventTypeParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	EventType   string `db:"event_type" json:"eventType"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListTimelineEventsByEventType(ctx context.Context, arg ListTimelineEventsByEventTypeParams) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByEventType,
		arg.WorkspaceID,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEventsByWorkspace = `-- name: ListTimelineEventsByWorkspace :many
SELECT id, workspace_id, entity_type, entity_id, actor_id, event_type, old_value, new_value, context, created_at
FROM timeline_event
WHERE workspace_id = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListTimelineEventsByWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListTimelineEventsByWorkspace(ctx context.Context, arg ListTimelineEventsByWorkspaceParams) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
