// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package sqlcgen

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :exec

INSERT INTO workspace (id, name, slug, settings, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
`

type CreateWorkspaceParams struct {
	ID        string  `db:"id" json:"id"`
	Name      string  `db:"name" json:"name"`
	Slug      string  `db:"slug" json:"slug"`
	Settings  *string `db:"settings" json:"settings"`
	CreatedAt string  `db:"created_at" json:"createdAt"`
	UpdatedAt string  `db:"updated_at" json:"updatedAt"`
}

// SQL queries for workspace table
// Task 1.2.7: sqlc-annotated queries
// Note: RETURNING * not supported by sqlc SQLite parser — use :exec + GetByID pattern.
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
?;

DELETE FROM workspace
WHERE id =
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
);

SELECT id, name, slug, settings, created_at, updated_at
FROM workspace
WHERE id = ?
LIMIT
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
1;

SELECT id, name, slug, settings, created_at, updated_at
FROM workspace
WHERE slug = ?
LIMIT
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
1;

SELECT id, name, slug, settings, created_at, updated_at
FROM workspace
ORDER BY name A
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
C;

UPDATE workspace
SET name       = ?,
    slug       = ?,
    settings   = ?,
    updated_at = ?
WHERE id =
`

type UpdateWorkspaceParams struct {
	Name      string  `db:"name" json:"name"`
	Slug      string  `db:"slug" json:"slug"`
	Settings  *string `db:"settings" json:"settings"`
	UpdatedAt string  `db:"updated_at" json:"updatedAt"`
	ID        string  `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Name,
		arg.Slug,
		arg.Settings,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
