// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workflow.sql

package sqlcgen

import (
	"context"
	"time"
)

const createWorkflow = `-- name: CreateWorkflow :one

INSERT INTO workflow (
    id, workspace_id, agent_definition_id, parent_version_id, name, description,
    dsl_source, spec_source, version, status, created_by_user_id, archived_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID                string     `db:"id" json:"id"`
	WorkspaceID       string     `db:"workspace_id" json:"workspaceId"`
	AgentDefinitionID *string    `db:"agent_definition_id" json:"agentDefinitionId"`
	ParentVersionID   *string    `db:"parent_version_id" json:"parentVersionId"`
	Name              string     `db:"name" json:"name"`
	Description       *string    `db:"description" json:"description"`
	DslSource         string     `db:"dsl_source" json:"dslSource"`
	SpecSource        *string    `db:"spec_source" json:"specSource"`
	Version           int64      `db:"version" json:"version"`
	Status            string     `db:"status" json:"status"`
	CreatedByUserID   *string    `db:"created_by_user_id" json:"createdByUserId"`
	ArchivedAt        *time.Time `db:"archived_at" json:"archivedAt"`
	CreatedAt         time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time  `db:"updated_at" json:"updatedAt"`
}

// AGENT_SPEC Phase 2: Workflow foundation queries
func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.WorkspaceID,
		arg.AgentDefinitionID,
		arg.ParentVersionID,
		arg.Name,
		arg.Description,
		arg.DslSource,
		arg.SpecSource,
		arg.Version,
		arg.Status,
		arg.CreatedByUserID,
		arg.ArchivedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.ParentVersionID,
		&i.Name,
		&i.Description,
		&i.DslSource,
		&i.SpecSource,
		&i.Version,
		&i.Status,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflow
WHERE id = ? AND workspace_id = ?
`

type DeleteWorkflowParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, arg.ID, arg.WorkspaceID)
	return err
}

const getActiveWorkflowByName = `-- name: GetActiveWorkflowByName :one
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE workspace_id = ? AND name = ? AND status = 'active'
LIMIT 1
`

type GetActiveWorkflowByNameParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Name        string `db:"name" json:"name"`
}

func (q *Queries) GetActiveWorkflowByName(ctx context.Context, arg GetActiveWorkflowByNameParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getActiveWorkflowByName, arg.WorkspaceID, arg.Name)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.ParentVersionID,
		&i.Name,
		&i.Description,
		&i.DslSource,
		&i.SpecSource,
		&i.Version,
		&i.Status,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE id = ? AND workspace_id = ?
LIMIT 1
`

type GetWorkflowByIDParams struct {
	ID          string `db:"id" json:"id"`
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowByID, arg.ID, arg.WorkspaceID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.ParentVersionID,
		&i.Name,
		&i.Description,
		&i.DslSource,
		&i.SpecSource,
		&i.Version,
		&i.Status,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByNameAndVersion = `-- name: GetWorkflowByNameAndVersion :one
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE workspace_id = ? AND name = ? AND version = ?
LIMIT 1
`

type GetWorkflowByNameAndVersionParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Name        string `db:"name" json:"name"`
	Version     int64  `db:"version" json:"version"`
}

func (q *Queries) GetWorkflowByNameAndVersion(ctx context.Context, arg GetWorkflowByNameAndVersionParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowByNameAndVersion, arg.WorkspaceID, arg.Name, arg.Version)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.ParentVersionID,
		&i.Name,
		&i.Description,
		&i.DslSource,
		&i.SpecSource,
		&i.Version,
		&i.Status,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowVersionsByName = `-- name: ListWorkflowVersionsByName :many
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE workspace_id = ? AND name = ?
ORDER BY version DESC, created_at DESC
`

type ListWorkflowVersionsByNameParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Name        string `db:"name" json:"name"`
}

func (q *Queries) ListWorkflowVersionsByName(ctx context.Context, arg ListWorkflowVersionsByNameParams) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowVersionsByName, arg.WorkspaceID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.ParentVersionID,
			&i.Name,
			&i.Description,
			&i.DslSource,
			&i.SpecSource,
			&i.Version,
			&i.Status,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByStatus = `-- name: ListWorkflowsByStatus :many
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE workspace_id = ? AND status = ?
ORDER BY created_at DESC
`

type ListWorkflowsByStatusParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspaceId"`
	Status      string `db:"status" json:"status"`
}

func (q *Queries) ListWorkflowsByStatus(ctx context.Context, arg ListWorkflowsByStatusParams) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsByStatus, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.ParentVersionID,
			&i.Name,
			&i.Description,
			&i.DslSource,
			&i.SpecSource,
			&i.Version,
			&i.Status,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByWorkspace = `-- name: ListWorkflowsByWorkspace :many
SELECT id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at FROM workflow
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowsByWorkspace(ctx context.Context, workspaceID string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentDefinitionID,
			&i.ParentVersionID,
			&i.Name,
			&i.Description,
			&i.DslSource,
			&i.SpecSource,
			&i.Version,
			&i.Status,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflow
SET agent_definition_id = ?, description = ?, dsl_source = ?, spec_source = ?,
    status = ?, archived_at = ?, updated_at = ?
WHERE id = ? AND workspace_id = ?
RETURNING id, workspace_id, agent_definition_id, parent_version_id, name, description, dsl_source, spec_source, version, status, created_by_user_id, archived_at, created_at, updated_at
`

type UpdateWorkflowParams struct {
	AgentDefinitionID *string    `db:"agent_definition_id" json:"agentDefinitionId"`
	Description       *string    `db:"description" json:"description"`
	DslSource         string     `db:"dsl_source" json:"dslSource"`
	SpecSource        *string    `db:"spec_source" json:"specSource"`
	Status            string     `db:"status" json:"status"`
	ArchivedAt        *time.Time `db:"archived_at" json:"archivedAt"`
	UpdatedAt         time.Time  `db:"updated_at" json:"updatedAt"`
	ID                string     `db:"id" json:"id"`
	WorkspaceID       string     `db:"workspace_id" json:"workspaceId"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflow,
		arg.AgentDefinitionID,
		arg.Description,
		arg.DslSource,
		arg.SpecSource,
		arg.Status,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentDefinitionID,
		&i.ParentVersionID,
		&i.Name,
		&i.Description,
		&i.DslSource,
		&i.SpecSource,
		&i.Version,
		&i.Status,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
