#!/usr/bin/env python3
"""Diff-based maintainability guard for fenix Go, RN, and BFF code.

Adapted from DubBridge check-maintainability.py; key differences:
  - Path classifiers: Go (internal/pkg/cmd), RN (mobile/), BFF (bff/)
  - Rust-specific checks removed: #[cfg(test)] boundary splitting, .unwrap()/.expect() gate
  - Go test detection: _test.go suffix (not cfg block)
  - Env var: FENIX_MAINTAINABILITY_BASE (replaces DUBBRIDGE_MAINTAINABILITY_BASE)
  - Budgets tuned for Go/TS file sizes
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "code generated",
    "do not edit",
    "generated by",
)


@dataclass(frozen=True)
class Profile:
    name: str
    added_block_budget: int
    repeated_line_budget: int
    duplicate_window: int
    declaration_budget: int
    duplicate_min_chars: int
    generic_name_budget: int
    long_line_budget: int


@dataclass(frozen=True)
class AddedLine:
    path: str
    text: str
    hunk: int
    line_no: int


@dataclass(frozen=True)
class Violation:
    path: str
    message: str


# Go source is typically larger than Rust; budgets are set generously to avoid
# false positives on legitimate handler or service additions.
GO_SOURCE = Profile(
    name="Go source",
    added_block_budget=80,
    repeated_line_budget=10,
    duplicate_window=4,
    declaration_budget=50,
    duplicate_min_chars=90,
    generic_name_budget=12,
    long_line_budget=20,
)
GO_TEST = Profile(
    name="Go test",
    added_block_budget=150,
    repeated_line_budget=12,
    duplicate_window=5,
    declaration_budget=80,
    duplicate_min_chars=120,
    generic_name_budget=20,
    long_line_budget=30,
)
MOBILE_SOURCE = Profile(
    name="RN/TS source",
    added_block_budget=50,
    repeated_line_budget=4,
    duplicate_window=3,
    declaration_budget=25,
    duplicate_min_chars=70,
    generic_name_budget=8,
    long_line_budget=10,
)
MOBILE_TEST = Profile(
    name="RN/TS test",
    added_block_budget=120,
    repeated_line_budget=6,
    duplicate_window=5,
    declaration_budget=50,
    duplicate_min_chars=110,
    generic_name_budget=14,
    long_line_budget=15,
)
BFF_SOURCE = Profile(
    name="BFF source",
    added_block_budget=60,
    repeated_line_budget=6,
    duplicate_window=4,
    declaration_budget=30,
    duplicate_min_chars=80,
    generic_name_budget=10,
    long_line_budget=12,
)

GENERIC_NAME_RE = re.compile(
    r"\b("
    r"generated[a-zA-Z0-9_]*|"
    r"temp[a-zA-Z0-9_]*|"
    r"placeholder[a-zA-Z0-9_]*|"
    r"foo|bar|baz|qux|"
    r"value\d+|item\d+|field\d+|data\d+|result\d+|thing\d+"
    r")\b"
)


def run_git(args: List[str]) -> str:
    result = subprocess.run(
        ["git"] + args,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def discover_base(explicit_base: Optional[str]) -> Optional[str]:
    candidates = [
        explicit_base,
        os.environ.get("FENIX_MAINTAINABILITY_BASE"),
        "origin/main",
        "HEAD",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        result = subprocess.run(
            ["git", "rev-parse", "--verify", candidate],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0:
            return candidate
    return None


def changed_files(base: Optional[str]) -> List[str]:
    if base is None:
        output = run_git(["diff", "--name-only"])
    else:
        output = run_git(["diff", "--name-only", base, "--"])
    return sorted({line.strip() for line in output.splitlines() if line.strip()})


def classify_path(path: str) -> Optional[Profile]:
    # Go: internal/, pkg/, cmd/ — test files use _test.go suffix
    if re.match(r"^(internal|pkg|cmd)/.*\.go$", path):
        return GO_TEST if path.endswith("_test.go") else GO_SOURCE
    # React Native / TypeScript
    if re.match(r"^mobile/(src|__tests__)/.*\.(ts|tsx)$", path):
        if "__tests__" in path or ".test." in path or path.endswith(".spec.ts"):
            return MOBILE_TEST
        return MOBILE_SOURCE
    # BFF (Express/TypeScript) — exclude test files
    if re.match(r"^bff/.*\.ts$", path) and ".test." not in path and ".spec." not in path:
        return BFF_SOURCE
    return None


def parse_added_lines(diff_text: str) -> List[AddedLine]:
    current_path: Optional[str] = None
    current_hunk = 0
    added_line_no = 0
    records: List[AddedLine] = []

    for raw_line in diff_text.splitlines():
        if raw_line.startswith("diff --git "):
            current_path = None
            current_hunk = 0
            added_line_no = 0
            continue
        if raw_line.startswith("+++ b/"):
            current_path = raw_line[6:]  # removeprefix("+++ b/") without 3.9+ method
            continue
        if raw_line.startswith("@@ "):
            current_hunk += 1
            match = re.search(r"\+(\d+)", raw_line)
            added_line_no = int(match.group(1)) if match else 0
            continue
        if raw_line.startswith("+") and not raw_line.startswith("+++"):
            if current_path is not None and classify_path(current_path) is not None:
                records.append(
                    AddedLine(
                        path=current_path,
                        text=raw_line[1:],
                        hunk=current_hunk,
                        line_no=added_line_no,
                    )
                )
            added_line_no += 1

    return records


def added_lines_for(base: Optional[str], files: List[str]) -> List[AddedLine]:
    code_files = [p for p in files if classify_path(p) is not None and Path(p).exists()]
    if not code_files:
        return []
    args = ["diff", "--unified=0", "--no-color"]
    if base is not None:
        args.append(base)
    args += ["--"] + code_files
    return parse_added_lines(run_git(args))


def is_meaningful_line(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    if stripped in {"{", "}", "},", ");", "];", "};", ")", "]"}:
        return False
    if stripped.startswith(("//", "/*", "*", "#")):
        return False
    return True


def normalize_line(text: str) -> str:
    stripped = text.strip()
    stripped = re.sub(r"\s+", " ", stripped)
    return stripped.rstrip(",;")


def is_declaration_line(path: str, text: str) -> bool:
    normalized = normalize_line(text)
    profile = classify_path(path)
    if profile in (GO_SOURCE, GO_TEST):
        return bool(
            re.match(
                r"^(func|type|var|const|import|package)\b",
                normalized,
            )
        )
    # TS/RN and BFF
    return bool(
        re.match(
            r"^(export )?(async )?function\b|^(export )?const\b|"
            r"^(export )?(type|interface|class|enum)\b|^import\b",
            normalized,
        )
    )


def group_by_path(lines: Iterable[AddedLine]) -> Dict[str, List[AddedLine]]:
    grouped: Dict[str, List[AddedLine]] = {}
    for line in lines:
        grouped.setdefault(line.path, []).append(line)
    return grouped


def _longest_meaningful_run(hunk_lines: List[AddedLine]) -> int:
    max_run = current_run = 0
    for line in hunk_lines:
        if is_meaningful_line(line.text):
            current_run += 1
            if current_run > max_run:
                max_run = current_run
        else:
            current_run = 0
    return max_run


def check_added_blocks(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        hunk_buckets: Dict[int, List[AddedLine]] = {}
        for line in lines:
            hunk_buckets.setdefault(line.hunk, []).append(line)

        for hunk, hunk_lines in sorted(hunk_buckets.items()):
            longest = _longest_meaningful_run(hunk_lines)
            if longest > profile.added_block_budget:
                violations.append(
                    Violation(
                        path,
                        f"hunk {hunk} (longest contiguous run {longest} meaningful lines; "
                        f"budget is {profile.added_block_budget})",
                    )
                )
    return violations


def check_generated_markers(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        for line in lines:
            lower = line.text.lower()
            marker = next((m for m in GENERATED_MARKERS if m in lower), None)
            if marker is not None:
                violations.append(
                    Violation(path, f"generated-source marker '{marker}' added at line {line.line_no}")
                )
                break
    return violations


def check_repeated_lines(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 12
        ]
        counts = Counter(normalized)
        repeated = [(ln, cnt) for ln, cnt in counts.items() if cnt > profile.repeated_line_budget]
        if repeated:
            sample, count = sorted(repeated, key=lambda item: item[1], reverse=True)[0]
            violations.append(
                Violation(
                    path,
                    f"line repeated {count} times in added code; budget is "
                    f"{profile.repeated_line_budget}: {sample[:90]}",
                )
            )
    return violations


def check_declaration_bursts(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        declaration_count = sum(
            1
            for line in lines
            if is_meaningful_line(line.text) and is_declaration_line(path, line.text)
        )
        if declaration_count > profile.declaration_budget:
            violations.append(
                Violation(
                    path,
                    f"{declaration_count} declaration/import lines exceed {profile.name} "
                    f"declaration budget of {profile.declaration_budget}",
                )
            )
    return violations


def check_generic_name_bursts(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        count = sum(
            1
            for line in lines
            if is_meaningful_line(line.text) and GENERIC_NAME_RE.search(normalize_line(line.text))
        )
        if count > profile.generic_name_budget:
            violations.append(
                Violation(
                    path,
                    f"{count} generic generated-style identifiers exceed {profile.name} "
                    f"generic-name budget of {profile.generic_name_budget}",
                )
            )
    return violations


def check_long_line_bursts(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    violations: List[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        count = sum(
            1 for line in lines
            if is_meaningful_line(line.text) and len(line.text.rstrip()) >= 120
        )
        if count > profile.long_line_budget:
            violations.append(
                Violation(
                    path,
                    f"{count} added lines are 120+ chars, exceeding {profile.name} "
                    f"long-line budget of {profile.long_line_budget}",
                )
            )
    return violations


def check_duplicate_blocks(grouped: Dict[str, List[AddedLine]]) -> List[Violation]:
    seen: Dict[Tuple[str, ...], Tuple[str, int]] = {}
    violations: List[Violation] = []

    for path, lines in sorted(grouped.items()):
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 8
        ]
        if len(normalized) < profile.duplicate_window:
            continue

        for index in range(len(normalized) - profile.duplicate_window + 1):
            window = tuple(normalized[index: index + profile.duplicate_window])
            if len("\n".join(window)) < profile.duplicate_min_chars:
                continue
            previous = seen.get(window)
            if previous is not None and previous[0] != path:
                violations.append(
                    Violation(
                        path,
                        f"duplicates a {profile.duplicate_window}-line added block from "
                        f"{previous[0]} near added block {previous[1]}",
                    )
                )
                return violations
            seen.setdefault(window, (path, index + 1))

    return violations


def analyze_added_lines(added_lines: List[AddedLine]) -> List[Violation]:
    grouped = group_by_path(added_lines)
    violations: List[Violation] = []
    violations.extend(check_added_blocks(grouped))
    violations.extend(check_generated_markers(grouped))
    violations.extend(check_repeated_lines(grouped))
    violations.extend(check_declaration_bursts(grouped))
    violations.extend(check_generic_name_bursts(grouped))
    violations.extend(check_long_line_bursts(grouped))
    violations.extend(check_duplicate_blocks(grouped))
    return violations


def render_report(violations: List[Violation]) -> str:
    if not violations:
        return "Maintainability gate passed."
    lines = ["Maintainability gate failed:"]
    for violation in violations:
        lines.append(f"- {violation.path}: {violation.message}")
    lines.append("")
    lines.append("Split the change, remove generated bulk, or simplify duplicated code before pushing.")
    return "\n".join(lines)


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", help="git revision to diff against")
    parser.add_argument("--files", nargs="*", help="explicit files to inspect")
    args = parser.parse_args(argv)

    base = discover_base(args.base)
    files = args.files if args.files is not None else changed_files(base)
    added_lines = added_lines_for(base, files)
    violations = analyze_added_lines(added_lines)
    print(render_report(violations))
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
