// CLSF-77b-78: client-side SVG canvas render, visual edits, save, and generated-source diff.
export { BUILDER_SCRIPT } from './builderCanvasScript';
export const GRAPH_AUTHORING_STYLES = `.graph-toolbar { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; padding: 12px 14px; border-bottom: 1px solid var(--line); background: #fbfcfe; } .graph-toolbar input, .graph-toolbar select { height: 34px; border: 1px solid var(--line); border-radius: 6px; padding: 0 10px; color: var(--text); background: #ffffff; } .graph-toolbar button { height: 34px; border: 0; border-radius: 6px; padding: 0 10px; background: var(--accent); color: #ffffff; font-weight: 700; cursor: pointer; } .graph-toolbar button:disabled { cursor: not-allowed; opacity: 0.48; } .graph-node-shell[data-selected="true"] .graph-node { stroke-width: 4; } .graph-node-shell[data-connecting-source="true"] .graph-node { stroke-dasharray: 6 4; } .source-diff { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; padding: 12px 14px; border-top: 1px solid var(--line); background: #fbfcfe; } .source-diff pre { min-height: 120px; margin: 0; padding: 10px; overflow: auto; border: 1px solid var(--line); border-radius: 6px; color: var(--text); background: #ffffff; font: 12px/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }`;
export const GENERATED_SOURCE_DIFF = `<div class="source-diff" aria-label="Generated source diff"><pre id="builder-generated-dsl"></pre><pre id="builder-generated-spec"></pre></div>`;
export const GRAPH_CANVAS_PLACEHOLDER = `<div id="builder-canvas-root" role="img" aria-label="Dynamic workflow graph canvas"></div>`;
const escAttr = (v: string) => v.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
export function renderGraphAuthoringControls(workflowId: string): string {
  return `<div class="graph-toolbar" aria-label="Graph authoring controls"><select id="builder-add-node-kind" aria-label="Node kind"><option value="workflow">workflow</option><option value="trigger">trigger</option><option value="action">action</option><option value="decision">decision</option><option value="grounds">grounds</option><option value="permit">permit</option><option value="delegate">delegate</option><option value="invariant">invariant</option><option value="budget">budget</option></select><input id="builder-add-node-label" type="text" placeholder="Node label" aria-label="Node label"><button id="builder-add-node" type="button">Add</button><button id="builder-delete-node" type="button" disabled>Delete</button><button id="builder-connect-node" type="button" disabled>Connect</button><button id="builder-save-graph" type="button" data-workflow-id="${escAttr(workflowId)}" data-save-action="/bff/builder/visual-authoring/${encodeURIComponent(workflowId)}">Save graph</button><span class="preview-status" id="builder-connect-status">Connect idle</span></div>`;
}
